### ISSUE TITLE
Browserlist not supported as autoprefixer config?

### ISSUE THREAD

**Issue by joecdeeson** [ben-eb/cssnano#103]
In the context of a gulp task...

```javascript
            .pipe(plugins.postcss([
                autoprefixer({browsers: browserslist()})
            ]))
```

^ produces the expected results (uses browserslist file at project root for prefixes)

```javascript
            .pipe(plugins.postcss([
                cssnano({
                    autoprefixer: {browsers: browserslist}
                })
            ]))
```

^ Doesn't autoprefix

Does anyone know if i'm using the wrong syntax or if this could be a cssnano bug?

I'm currently using the following but this feels a bit clumsy:

```javascript
            .pipe(plugins.postcss([
                autoprefixer({browsers: browserslist()}),
                cssnano({
                    autoprefixer: false
                })
            ]))
```

**Comment by ben-eb** [comment]
By default, we only use autoprefixer for removing old prefixed properties as this is a compression tool. :smile:

https://github.com/ben-eb/cssnano/issues/69

**Comment by joecdeeson** [comment]
Ah ok cheers - I thought it was a weird thing to be doing :)
