### ISSUE TITLE
bump autoprefixer version

### ISSUE THREAD

**Issue by evilebottnawi** [ben-eb/cssnano#105]
usage cssnano and browserslist(last version) break deps, cssnano use autoprefixer old version(this version use browserslist@'~1.0.1').

```bash
npm WARN unmet dependency /some_path/node_modules/cssnano/node_modules/autoprefixer requires browserslist@'~1.0.1' but will load
npm WARN unmet dependency /some_path/node_modules/browserslist,
npm WARN unmet dependency which is version 1.1.0
```

**Comment by ben-eb** [comment]
Can you try reinstalling cssnano? We depend on autoprefixer 6 and up (until 7), as you can see our dependencies are not out of date.

https://gemnasium.com/ben-eb/cssnano
https://github.com/ben-eb/cssnano/blob/master/package.json#L21
