### ISSUE TITLE
Minify Angular Material dialogs

### ISSUE THREAD

**Issue by bampakoa** [ben-eb/cssnano#109]
Hi,
I am currently using [**gulp-cssnano**](https://github.com/ben-eb/gulp-cssnano) to minify my application that uses Angular Material. I have noticed that, after minification, angular material dialogs cannot receive input from the user by any means. The only action that can be done is pressing ESC to close the dialog.

I have also noticed that other people face the same problem in [this](https://github.com/jadjoubran/laravel5-angular-material-starter/issues/144) issue.

Angular version: 1.3.20
Angular Material version: 1.0.3
Gulp-CssNano version: 2.1.0
CssNano version: 3.4.0

**Comment by ben-eb** [comment]
Can you try with `{safe: true}` and report back?

**Comment by bampakoa** [comment]
@ben-eb That worked! Thanks very much.

**Comment by ben-eb** [comment]
No problem. :smile:

**Comment by jefersonmanjos** [comment]
+1
