### ISSUE TITLE
gulp-cssnano breaks with liquid statements

### ISSUE THREAD

**Issue by goldsteinr** [ben-eb/cssnano#110]
[15:03:37] Starting 'scss'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: all.scss:1832:30: Unknown word
.divider {
    border-top: 1px solid {{ settings.color-border }};
                

Is it possible to use cssnano with liquid statements?

**Comment by ben-eb** [comment]
No, it isn't. It's not valid CSS so PostCSS does not parse these statements. If you would like to write an extension for the default parser that supports this syntax then we could parse these tags, but otherwise it seems like a really niche use case. I don't have time to write this feature.

**Comment by ben-eb** [comment]
I'm going to go ahead and close this issue as it isn't directly related to cssnano. We can only provide this support through a custom syntax for PostCSS, which I don't really have the time to write.
