### ISSUE TITLE
Information regarding `filterOptimiser`

### ISSUE THREAD

**Issue by s10wen** [ben-eb/cssnano#118]
Noticed there's a `filterOptimiser`:
https://github.com/ben-eb/cssnano/search?q=filterOptimiser&type=Code&utf8=%E2%9C%93

But couldn't find any information regarding what it does at:
http://cssnano.co/optimisations/

**Comment by ben-eb** [comment]
Basically it is there to remove spaces in & around filter functions and commas. It's likely to be merged with other functionality for v4. Not sure if it is worth documenting this now. :smile:

https://github.com/ben-eb/cssnano/issues/88

**Comment by s10wen** [comment]
Gotcha :+1:

**Comment by ben-eb** [comment]
Note that this is now properly documented for version 3.x.

http://cssnano.co/optimisations/#filteroptimiser
