### ISSUE TITLE
Allow usage of postcss-safe-parser

### ISSUE THREAD

**Issue by devinus** [ben-eb/cssnano#119]

**Comment by ben-eb** [comment]
This should work already using the options object; it passes options both to the plugin and PostCSS itself. Can you try loading postcss-safe-parser through the parser option? Can't test it right now, I'm on mobile. :smile:

**Comment by TrySound** [comment]
@devinus Which runner do you use?

**Comment by ben-eb** [comment]
```js
var cssnano = require('cssnano');
var safeParser = require('postcss-safe-parser');

cssnano().process('a { color: blue', {parser: safeParser}).then(result => {
    console.log(result.css);
});

//=> a{color:blue}
```

**Comment by devinus** [comment]
Apologies. I think GitHub ate my response. This ended up working after using the `parser` option at the top level like your example shows. :+1:

**Comment by ben-eb** [comment]
Awesome. :smiley:
