### ISSUE TITLE
Include autoprefixer in a 'removal only mode'.

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/cssnano#13]
I am looking to add this feature when Autoprefixer supports it (https://github.com/postcss/autoprefixer/issues/446), and when this issue is also resolved in PostCSS https://github.com/postcss/postcss/issues/325.

**Comment by MoOx** [comment]
This is kind of weird since autoprefixer will generally be used before cssnano so it will be done already right ?

**Comment by ben-eb** [comment]
This kind of optimisation could be disabled if Autoprefixer was already found in the chain (https://github.com/postcss/postcss/issues/325), it could even be off by default.

**Comment by ben-eb** [comment]
Fixed in https://github.com/ben-eb/cssnano/commit/84b55e6d7832200140aa9a0d863526f9d4e19411
