### ISSUE TITLE
Keyframe names in separated file

### ISSUE THREAD

**Issue by geedmo** [ben-eb/cssnano#136]
When you define keyframes in one file and then use them in another file, animations don't work because their names don't match. I understand that cssnano can't see where I'm using the minified keyframe names. Is possible to keep original keyframes name ?

After run cssnano:

some.css
``` css
@keyframes a { ... }
```
another.css
``` css
animation: someAnimation 0.5s;
```

Thanks

**Comment by ben-eb** [comment]
https://github.com/ben-eb/postcss-reduce-idents/issues/5 is tracking this issue.

You can disable it with `{reduceIdents: false}`.
