### ISSUE TITLE
cssnano breaks PDF styles

### ISSUE THREAD

**Issue by markushausammann** [ben-eb/cssnano#141]
content: counter(page) " / " counter(pages);

is turned into

    content: counter(a) " / " counter(b);

which breaks the PDF page numbering.

**Comment by ben-eb** [comment]
This feature can be disabled by https://github.com/ben-eb/postcss-reduce-idents#counter -

```js
{
  reduceIdents: {counter: false}
}
```

Or simply:

```js
{
  reduceIdents: false
}
```

Looking into turning this option off by default for v4.
