### ISSUE TITLE
@keyframes name restrictions

### ISSUE THREAD

**Issue by martin-pettersson** [ben-eb/cssnano#149]
@keyframes seems to have some restrictions to the animation name.
For instance "a" or "b" is not allowed and breaks the animation.

**Comment by ben-eb** [comment]
Are you sure? I use this transform on http://cssnano.co/, it affects the GitHub logo animation in the top right and it works fine for me using `a` as an identifier. Is it perhaps another transform?

**Comment by martin-pettersson** [comment]
Terribly sorry it has nothing to do with the name, it was a simple (yet hard to find) naming collision.
