### ISSUE TITLE
Fatal error: URI malformed

### ISSUE THREAD

**Issue by plugin-kevin** [ben-eb/cssnano#156]
I'm getting an error from CSS Nano on this line of CSS:
`    background: url("data:image/svg+xml;charset=utf-8,%3C?xml version='1.0' encoding='utf-8'?%3E%3Csvg id='Layer_1' xmlns='http://www.w3.org/2000/svg' width='80' height='80' viewBox='-59 61 80 80' enable-background='new -59 61 80 80'%3E%3Cstyle%3E.st0{fill:none;stroke:%230cbfff;stroke-width:4}.st1{fill:%230cbfff}%3C/style%3E%3Cfilter id='dropshadow' height='130%'%3E%3CfeGaussianBlur in='SourceAlpha' stdDeviation='3'/%3E%3CfeOffset dx='-2' dy='2' result='offsetblur'/%3E%3CfeMerge%3E%3CfeMergeNode/%3E%3CfeMergeNode in='SourceGraphic'/%3E%3C/feMerge%3E%3C/filter%3E%3Ccircle class='st0' cx='-17' cy='100' r='32.8' filter='url(%23dropshadow)'/%3E%3Cpath class='st1' filter='url(%23dropshadow)' d='M-29.8 82L3.9 99.8l-33.7 17.4z'/%3E%3C/svg%3E") top center no-repeat;`

As far as I can tell, the URL is valid, and in fact the image renders in Safari and Chrome.

**Comment by ben-eb** [comment]
Try disabling `postcss-svgo` as a temporary solution - via API;

```js
{
  svgo: false
}
```

or CLI;

```
$ cssnano --no-svgo
```

/cc @TrySound

**Comment by TrySound** [comment]
@plugin-kevin Seems like you use old version of postcss-svgo (part of cssnano). Try to reinstall your node_modules.

**Comment by plugin-kevin** [comment]
@TrySound `npm update` solved it. Thanks!

**Comment by keoshi** [comment]
Also getting that error, but updating the modules didn't fix it for me.

Running:

`gulp-cssnano 2.1.1`
`postcss-svgo 2.1.2`
