### ISSUE TITLE
rgb2hsl bug

### ISSUE THREAD

**Issue by lzl124631x** [ben-eb/cssnano#157]
compass will translate `rgba(#F1F1F1, .9)` into `rgba(241, 241, 241, 0.9)`, but cssnano will compress it into `hsla(0,0%,95%,.9)`.

However, `rgb(241, 241, 241)` actually equals `hsl(0,0%,94.5%)`. So I think cssnano rounded it up, but it will result in UI bug, though minor.

**Comment by ben-eb** [comment]
This looks like a bug with the https://github.com/Qix-/color module.

```js
const color = require('color');
console.log(color('rgb(241, 241, 241)').hslString());
```

Could you raise this issue there please?
