### ISSUE TITLE
Minified css from sass files is broken, because of a backslash in font declaration, when creating build with "-p" option

### ISSUE THREAD

**Issue by tonitone** [ben-eb/cssnano#158]
Hi,

if i build my sources in Webpack with the "-p" option to minified them, my styles get broken.

I don't know how the backslash after the "...14px/" comes into my css file.

~~~
.fa {
    display: inline-block;
    font: normal normal normal 14px/\ 1 FontAwesome;
...       
~~~
Thanks
Toni

**Comment by ben-eb** [comment]
Could you please provide the input CSS so I can reproduce?

**Comment by tonitone** [comment]
Hey, 

thanks for the quick response.

I use webpack for build my packages. When I build the font-awesom.scss file without compression, everything looks fine. But when I create my build with the "-p" option in webpack, to compress the styles, it produce the said error.

[dev.zip](https://github.com/ben-eb/cssnano/files/198207/dev.zip)

**Comment by ben-eb** [comment]
I'm not sure where this is coming from, I tried it in my webpack build and it came out fine. Same with the CLI too. Perhaps it is some other module in your environment?

**Comment by tonitone** [comment]
Hi Ben,

I don't know, which other module could be the problem.

For now I have split the font-shorthand properties to sperate CSS properties:

~~~
font-style:normal;
font-variant:normal;
font-weight:normal;
font-size:#{$fa-font-size-base};
line-height:#{$fa-line-height-base};
font-family: FontAwesome;
~~~

**Comment by ben-eb** [comment]
I can better debug this if you can produce some minimal test case that exhibits this issue. As is I can't reproduce... :confused:

**Comment by tonitone** [comment]
Thanks, but the project time is running :) 
I'll try to live with my workaround.
