### ISSUE TITLE
Removes font-family when in CSS custom property 

### ISSUE THREAD

**Issue by furzeface** [ben-eb/cssnano#162]
Seems to only be when I use `font-family` though so far, other custom properties are alright.

I put a stripped down test case together here: https://github.com/furzeface/cssnano-test-case

I've read a few issue threads - is there a feature at the moment that allows for experimental properties to be optimised, or is it in the pipeline still? Thanks :)

**Comment by furzeface** [comment]
I'd like to help by the way, if you can point me in the right direction I'll investigate :octocat:

**Comment by ben-eb** [comment]
Looks like it's in `postcss-minify-font-values`. For now you can do `$ cssnano no-minifyFontValues` or use this options object `{minifyFontValues: false}`.

**Comment by furzeface** [comment]
Great, thanks :smile: I guess all of the custom properties stuff is in the pipeline for the future too, so I'll be interested to see how this works out :blush: Nice one, thank you.

**Comment by ben-eb** [comment]
Fixed in postcss-minify-font-values `1.0.5`.

**Comment by furzeface** [comment]
ace, thanks :)
