### ISSUE TITLE
Doesn't work with postcss-modules

### ISSUE THREAD

**Issue by just-boris** [ben-eb/cssnano#163]
I am trying to make [`postcss-modules`](https://github.com/outpunk/postcss-modules) work with `cssnano`.

Let's see a simple example: https://gist.github.com/just-boris/7bc3881c5f92c916f674e6d4f46c06a7 When both plugins enabled I am getting the following error:

```
TypeError: Cannot read property 'type' of undefined
    at /Users/just-boris/postcss-bug/node_modules/postcss-discard-unused/dist/index.js:93:48
    at /Users/just-boris/postcss-bug/node_modules/postcss/lib/container.js:73:26
```

The thing is that `postcss-modules` generate nodes, that don't have `parent` property. So, then it fails when cssnano tries to read them.

I filed issue in the main repo, because it happened in several children projects:

* postcss-discard-duplicates: https://github.com/ben-eb/postcss-discard-duplicates/blob/master/src/index.js#L19
* postcss-discard-unused: https://github.com/ben-eb/postcss-discard-unused/blob/master/src/index.js#L63

Maybe I missed something and it also happens in some other plugins.

**Comment by ben-eb** [comment]
ping @ai

**Comment by ai** [comment]
ping @outpunk :)

Seems like AST become broken.

**Comment by just-boris** [comment]
@ai you meant that AST declaration must always have the parent property?

So, then the issue can be in some postcss-modules dependencies:
* https://github.com/css-modules/postcss-modules-extract-imports/blob/master/src/index.js#L59 
* https://github.com/css-modules/postcss-modules-scope/blob/master/src/index.js#L154

I don't know whether it can be fixed in plugin, but I think postcss core can take care of proper parent property when you are calling `css.append()`

**Comment by ai** [comment]
@just-boris ouh :( I will create a issues in css-modules

**Comment by ai** [comment]
https://github.com/css-modules/postcss-modules-extract-imports/issues/59
https://github.com/css-modules/postcss-modules-extract-imports/issues/59

**Comment by ben-eb** [comment]
Going to close this in favour of those postcss-modules issues linked above.
