### ISSUE TITLE
"s" symbol wrongly removed from animation-delay

### ISSUE THREAD

**Issue by RavenXce** [ben-eb/cssnano#166]
Currently, `animation-delay: 0s` is being converted into `animation-delay:0` by nanocss.

However, `animation-delay: 0` is invalid as it is a `time` data type, not `length`. 
(See: https://developer.mozilla.org/en-US/docs/Web/CSS/time)

While this is normally not a problem as 0s is the default value, it can cause issues when the delay is generated programatically through scss in the `animation` shorthand, thereby breaking the whole statement.

**Example**
```
@mixin loading-ball($n, $radius, $ceiling) {
  $position: ($n - 1)*($radius*3);
  $top: -$ceiling;
  $delay: ($n - 1)*-0.08s;
  animation: ball-#{$position}-#{$ceiling} 1.4s ease infinite $delay;
  @at-root {
    @keyframes ball-#{$position}-#{$ceiling} {
      from {
        left: $position;
        top: 0;
      }
      ...
  }
}
```
The above produces a valid animation directive for `$n: 1`, but becomes invalid after minification.

**Comment by ben-eb** [comment]
Are you sure? I just tried it with the CLI;

```css
h1{animation-delay: 0s}
```

Output:

```css
h1{animation-delay:0s}
```

Is it not the preprocessor rounding this value and dropping the `s`?

**Comment by RavenXce** [comment]
Apologies. I actually only happens for the `animation` shorthand and I assumed it affects both. I'll edit the issue to reflect that.

**Comment by ben-eb** [comment]
Could you attach a CSS example that reproduces this error please?

**Comment by RavenXce** [comment]
Apologies, I used the CLI and confirmed it is some other pre-processor that is dropping the `s`.

**Comment by ben-eb** [comment]
Alright, cool. :+1:
