### ISSUE TITLE
Problem with minimizing calc(100% - var(--my-var)) to calc(1 - var(--my-var))

### ISSUE THREAD

**Issue by rickychien** [ben-eb/cssnano#168]
I'm using css-loader (with cssnano@3.5.2) to minimize my css but it breaks my website style since it parsed

```css
calc(100% - var(--my-var))
```

to

```css
calc(1 - var(--my-var))
```

any idea? thanks!

**Comment by ben-eb** [comment]
Thanks for the report, it was resolved in the latest release of reduce-css-calc. 👍

**Comment by rickychien** [comment]
Awesome!
