### ISSUE TITLE
Weird warnings when consuming this with webpack

### ISSUE THREAD

**Issue by MoOx** [ben-eb/cssnano#17]
I have a specific need that not so specific: I am building a browser version of cssnext for the playground.
Not that cssnext embed cssnano I have weird notice when I make this build with webpack

It looks like some part of cssnano are being consumed via a require or something smiliar that make webpack think we want to consume some non js file.

```
WARNING in ./~/cssnano/index.js
Critical dependencies:
57:20-35 the request of a dependency is an expression
 @ ./~/cssnano/index.js 57:20-35

WARNING in ./~/cssnano/CHANGELOG.md
Module parse failed: /Users/MoOx/Sync/Development/cssnext/cssnext/node_modules/cssnano/CHANG
ELOG.md Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| # 1.2.0
|
| * Better support for merging properties without the existance of a shorthand
 @ ./~/cssnano ^\.\/.*$

WARNING in ./~/cssnano/LICENSE-MIT
Module parse failed: /Users/MoOx/Sync/Development/cssnext/cssnext/node_modules/cssnano/LICEN
SE-MIT Line 1: Unexpected identifier
You may need an appropriate loader to handle this file type.
| Copyright (c) Ben Briggs <beneb.info@gmail.com> (http://beneb.info)
|
| Permission is hereby granted, free of charge, to any person
 @ ./~/cssnano ^\.\/.*$

WARNING in ./~/cssnano/bin/cmd.js
Module parse failed: /Users/MoOx/Sync/Development/cssnext/cssnext/node_modules/cssnano/bin/c
md.js Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| #!/usr/bin/env node
|
| var fs = require('fs');
 @ ./~/cssnano ^\.\/.*$

WARNING in ./~/cssnano/README.md
Module parse failed: /Users/MoOx/Sync/Development/cssnext/cssnext/node_modules/cssnano/READM
E.md Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| # cssnano [![Build Status](https://travis-ci.org/ben-eb/cssnano.svg?branch=master)][ci] [!
[NPM version](https://badge.fury.io/js/cssnano.svg)][npm] [![Dependency Status](https://gemn
asium.com/ben-eb/cssnano.svg)][deps] [![Gitter](https://badges.gitter.im/Join Chat.svg)](htt
ps://gitter.im/ben-eb/cssnano?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_co
ntent=badge)
|
| > A modular minifier, built on top of the [PostCSS] ecosystem.
 @ ./~/cssnano ^\.\/.*$

WARNING in ./~/cssnano/bin/usage.txt
Module parse failed: /Users/MoOx/Sync/Development/cssnext/cssnext/node_modules/cssnano/bin/u
sage.txt Line 1: Unexpected token {
You may need an appropriate loader to handle this file type.
| Usage: cssnano [input] [output] {OPTIONS}
|
| Options:
 @ ./~/cssnano ^\.\/.*$
```

From what I see, you are doing some dynamic require() which is not ideal for 2 things:
- browser build
- not future proof (see es6 imports)

But I get the lazy loading.
Maybe you should consider using a solution similar like cssnext does ? https://github.com/cssnext/cssnext/blob/0a5d06f4c1a71b5b62d450029d46dfa6cba0b333/index.js#L38-L93
I know this is verbose, but having hardcoded require() make this easier to consume, especially for webpack and browserify.

**Comment by ben-eb** [comment]
Would there be a possible way of testing this integration?

**Comment by MoOx** [comment]
yeah, just build a standalone cssnano build with webpack. I will try to handle that for you when I get some time.

**Comment by MoOx** [comment]
Example here https://github.com/MoOx/eslint-loader/blob/master/test/index.js#L22-L36 of using webpack node js api with checking error and warnings :)

**Comment by ben-eb** [comment]
OK cool. I am not 100% sold on having a verbose require function wrapper. I think I would prefer an API like this:

```js
var calc = require('postcss-calc');

var processors = {
    'calc': 'calc'
};

// main function body
var plugins = Object.keys(processors);
var i = 0;

while (i < plugins.length) {
    var plugin = plugins[i++];
    postcss.use(plugin(opts));
}
```

**Comment by MoOx** [comment]
Sure.
You mean 

```
var processors = {
    'calc': calc
};
```

right ?

**Comment by ben-eb** [comment]
Yep, but thinking about it I will also need some means for the options namespace (https://github.com/ben-eb/cssnano/blob/master/index.js#L25-L26)

```js
var processors = {
    'postcss-merge-idents': {namespace: 'idents', processor: mergeIdents}
    'postcss-reduce-idents': {namespace: 'idents', processor: reduceIdents}
}
```

**Comment by ben-eb** [comment]
@MoOx I'm struggling with this; how can I get this test to pass? https://github.com/ben-eb/cssnano/commit/3e57020e2b98b313730bb48d8f1d080b5706ba31

**Comment by ben-eb** [comment]
Why would https://github.com/ben-eb/cssnano/commit/217df8ed63cb2067b3362d20147609b8188c47ad throw a CssSyntaxError? https://travis-ci.org/ben-eb/cssnano/jobs/64236255

**Comment by MoOx** [comment]
Not sure why. If I get some time I will take another look.

**Comment by MoOx** [comment]
I am on it.
