### ISSUE TITLE
Custom file extension for dir

### ISSUE THREAD

**Issue by dnepro** [ben-eb/cssnano#173]
I've got a [postcss-cli](https://github.com/postcss/postcss-cli) setup where i want all `*.css`-files to be minified into `filename-as-it-is.min.css` in the same directory without having to specify each file and the according output file on its own, because of the huge amount of files. Is there already a solution i missed out? Otherwise is it possible to include a cli-argument/option to set the file extension, like `--file-extension .min.css` or similar?

By the way, this is the command i run `node_modules/.bin/postcss -u cssnano --dir Web/Resources/Public/Styles/ Web/Resources/Public/Styles/*.css`

With kind regards.

PS: Or does this maybe even make more sense in postcss / postcss-cli?

**Comment by ben-eb** [comment]
Yep, it would be better to ask this in the postcss-cli repository. :smile:
