### ISSUE TITLE
cssnano removes @font-face

### ISSUE THREAD

**Issue by vlrprbttst** [ben-eb/cssnano#178]
I can't find any trace of my `@font-face` declarations in the cssnano processed final stylesheet. how do I prevent this? My fonts ain't loading.

thanks and sorry for the flood of questions :)

**Comment by ben-eb** [comment]
Likelihood is that those definitions are stripped out by [postcss-discard-unused](https://github.com/ben-eb/postcss-discard-unused#example), as it expects to find a matching `font-family` declaration to go along with the definition. You can turn this behaviour off with `{discardUnused: false}` (or `--no-discardUnused` from the CLI).

**Comment by vlrprbttst** [comment]
hi ben
with this configuration

```
            build: {
                options: {
                    map: false,
                    processors: [
                        require('cssnano')({autoprefixer: {browsers: 'last 2 version, IE 9'},minifyFontValues: {removeQuotes: false}, discardUnused: {discardUnused: false}})
                    ]
                },
                src: '_site/css/main.css'
            }
```

i still can't find the font face declaration.
should i do something different?

thanks and sorry for the hassle

**Comment by ben-eb** [comment]
```js
{
  discardUnused: false
}
```

Not this:

```js
{
  discardUnused: {discardUnused: false}
}
```
