### ISSUE TITLE
Bug v3.5.2: background-position

### ISSUE THREAD

**Issue by marcobiedermann** [ben-eb/cssnano#180]
CSSNano removes the second `background-position` value. Also keywords should be converted to percentage.

Input:
```
.selector {
  background-position: top center;
}
```

Output is:
```
.selector {
  background-position: top;
}
```

Output should be:
```
.selector {
  background-position: 0 50%;
}
```

This bug occurs in version 3.5.2

**Comment by ben-eb** [comment]
According to the spec, the `center` value is assumed if the property is a single value.

> If only one value is specified, the second value is assumed to be ‘`center`’.

https://drafts.csswg.org/css-backgrounds-3/#background-position

Also, the *first* value, when it is a `length` value and not a keyword is assumed to be the horizontal offset. So `background-position: 0` is actually equivalent to `background-position: left center` and therefore should not be transformed.

**Comment by marcobiedermann** [comment]
@ben-eb Thank you very much for your reply. I did not know that. I always learn something new :)
