### ISSUE TITLE
Full page overlay

### ISSUE THREAD

**Issue by marcobiedermann** [ben-eb/cssnano#182]
Both declaration will do the exact same. The first declaration uses `width` and `height` of `100%`, and has a length of `65` characters minified.
The second declarations uses `bottom`, `left`, `right` and `top` of `0` which has a length of `59` characters minified.

65 characters:

```
.selector {
  height: 100%;
  left: 0;
  top: 0;
  position: absolute;
  width: 100%;
}

.selector{height:100%;left:0;top:0;position:absolute;width:100%;}
```

59 characters:

```
.selector {
  bottom: 0;
  left: 0;
  right: 0;
  position: absolute;
  top: 0;
}

.selector{bottom:0;left:0;right:0;position:absolute;top:0;}
```

I know, this is hard to implement and does not save that much bytes but is in an improvement.
So I open up this for discussion :)

**Comment by ben-eb** [comment]
This needs a bit of thought; I'm going to cautiously pencil it in for 4.0, as an optional transform which I'd like testing before it would be enabled as a *safe* default transform. You're right in that it does not save many bytes, so it will be lower down the priority list. 😄

**Comment by luketeaford** [comment]
I think it would depend on a case by case basis and would require a lot of testing because it would be impossible to know the author's intention, but I would go further still and do:

`.selector {
  height: 100%;
  position: absolute;
  top: 0;
  width: 100%;
}

.selector{height:100%;position:absolute;top:0;width:100%;}
`

**Comment by Justineo** [comment]
The input and output are not equal if the elements match `.selector` if they have margins (and you can not tell that from CSS alone). Calculation logic differs between these two style rules: http://jsbin.com/gifutiqeye/2/edit?html,css,output

So if even we introduce this "optimization", it would be definitely **unsafe**.

**Comment by ben-eb** [comment]
Really solid test case, thanks a lot @Justineo. 💯

**Comment by chriseppstein** [comment]
This is also dangerous in the sense that it cascades differently. Selectors that don't override the original might override the optimized version.

Gonna just not do this.
