### ISSUE TITLE
Version 3.6.0 causes postcss module to break

### ISSUE THREAD

**Issue by dudabone** [ben-eb/cssnano#192]
Working with the latest release (3.6.0) causes the following error:

10:37:37 [ERROR] TypeError: Cannot read property 'value' of undefined
10:37:37 [ERROR]     at reduce (/node_modules/cssnano/dist/lib/reduceTimingFunctions.js:44:26)
10:37:37 [ERROR]     at walk (/node_modules/postcss-value-parser/lib/walk.js:7:22)
10:37:37 [ERROR]     at ValueParser.walk (/node_modules/postcss-value-parser/lib/index.js:18:5)
10:37:37 [ERROR]     at /node_modules/cssnano/dist/lib/reduceTimingFunctions.js:65:72
10:37:37 [ERROR]     at /node_modules/postcss/lib/container.js:100:28
10:37:37 [ERROR]     at /node_modules/postcss/lib/container.js:81:26
10:37:37 [ERROR]     at Rule.each (/node_modules/postcss/lib/container.js:68:22)
10:37:37 [ERROR]     at Rule.walk (/node_modules/postcss/lib/container.js:80:21)
10:37:37 [ERROR]     at /node_modules/postcss/lib/container.js:83:32
10:37:37 [ERROR]     at Root.each (/node_modules/postcss/lib/container.js:68:22)
10:37:37 [ERROR]     at Root.walk (/node_modules/postcss/lib/container.js:80:21)

does not happen when downgrading cssnano to 3.5.2

**Comment by ben-eb** [comment]
Fixed in `3.6.1`. Thanks for the report. 👍

**Comment by dudabone** [comment]
That was fast :) thanks for the fix!
