### ISSUE TITLE
String quote problem when using postcss-inline-svg

### ISSUE THREAD

**Issue by dan-gamble** [ben-eb/cssnano#196]
[PostCSS Inline SVG](https://github.com/TrySound/postcss-inline-svg)

[Broken line in question](https://gist.github.com/dan-gamble/63999f2114780e2063a5664fb4e6bd98#file-output-css-L1980)
[Input CSS](https://gist.github.com/dan-gamble/7aee75512de821cdd33028f56b735613)
[Input SVG](https://gist.githubusercontent.com/dan-gamble/189ab8cda4f69d64c805447c7c3d7a41/raw/06d0decc17d6c17ee5932294fd8e9d6b7f298800/svg.svg)

FWIW this is with `svgo` disabled on Nano. The opening quote for the `background-image` is an `'` where as the closing is an `"`. When `svgo` wasn't disabled both the opening and closing was an `'`.

If you need any more info just gimme a shout :)

**Comment by ben-eb** [comment]
Would you mind putting this together into a test repo for me please? Not sure where the problem could be yet. 😄

**Comment by dan-gamble** [comment]
Sure will do, probably won't be today but i'll try get a test repo up for you tomorrow 👍

**Comment by paras20xx** [comment]
@dan-gamble 
Your issue seems to be the same as the one I've sent a pull request for: https://github.com/ben-eb/postcss-normalize-url/pull/12

My issue is with Node JS v0.10

**Comment by paras20xx** [comment]
Whoops ... misread something ... probably not related.

**Comment by ben-eb** [comment]
Any updates?

**Comment by dan-gamble** [comment]
Sorry @ben-eb I've been in Miami, flying back today so i promise i'll attempt to get a minimal repo up this week :)

**Comment by dan-gamble** [comment]
I'm trying to recreate this but i can't.. I'm going to revert my code on this project to go back to using `postcss-inline-svg` and will see if i can get it to break again. If so i'll reopen this :)
