### ISSUE TITLE
Removing color-stop value of 0 in a linear-gradient 

### ISSUE THREAD

**Issue by darby3** [ben-eb/cssnano#208]
Using cssnano 3.7.0 (through grunt, following grunt-sass, through postcss following autoprefixer). I have a linear-gradient with a closing color-stop value of 0:

`border-image: 100% 0 0 linear-gradient(90deg, transparent calc(2vw - 3px), #00aeef 0);`

Cssnano removes the closing 0, breaking the gradient (well, the hard-stop where transparency ends and color begins). 

I've hacked around it by wrapping the 0 in a calc() in my sass file, which results in a plain old 0 at the end of the build process.

Happy to provide more details about my set-up if useful.

**Comment by ben-eb** [comment]
Thanks for reporting. 👍

This is resolved in postcss-minify-gradients `1.0.3`.
