### ISSUE TITLE
Warning: undefined [postcss-discard-empty]

### ISSUE THREAD

**Issue by mikestopcontinues** [ben-eb/cssnano#213]
With a recent update, cssnano has been outputting the following on every build for every file that has an empty rule. I can just disable postcss-reporter, but I don't think its a necessary message given that cssnano's reason for being is to compress css.

```
node_modules/sanitize.css/sanitize.css
undefined [postcss-discard-empty]
```

**Comment by ben-eb** [comment]
Duplicate of #212.

https://github.com/ben-eb/cssnano/issues/212#issuecomment-227114052
