### ISSUE TITLE
Investigate dropping `all and` in media queries

### ISSUE THREAD

**Issue by wooorm** [ben-eb/cssnano#215]
Hi folks! 👋

Per the [spec](http://www.w3.org/TR/css3-mediaqueries/#media0) (example 5):

> I.e. these are identical:
> 
> ``` css
> @media all and (min-width:500px) { … }
> @media (min-width:500px) { … }
> ```
> 
> As are these:
> 
> ``` css
> @media (orientation: portrait) { … }
> @media all and (orientation: portrait) { … }
> ```

It seems to me that those could be stripped, but from running cssnano myself it looks like they aren’t:

``` js
> n = require('cssnano')
> n.process('@media all and (min-width:500px){a{top:0}}', {svgo: false}).css
'@media all and (min-width:500px){a{top:0}}'
```

Thanks!

**Comment by ben-eb** [comment]
For some further reading, see the top two answers on this question:

http://stackoverflow.com/questions/8549529/what-is-the-difference-between-screen-and-only-screen-in-media-queries

**Comment by andyjansson** [comment]
:+1:

**Comment by ai** [comment]
looks good
