### ISSUE TITLE
The ::after notation (with two colons) converted to :after (one colon)

### ISSUE THREAD

**Issue by Olivia101** [ben-eb/cssnano#232]
The ::after notation (with two colons) which was introduced in CSS 3 is converted to :after (one colon).

For example my CSS3 code:
abbr[title]::after {
    content: " (" attr(title) ")";
  }

was converted to CSS2 code:
abbr[title]:after {
    content: " (" attr(title) ")";
  }

This change occurred when I compiled Bootstrap v4 .scss files using cssnano 3.7.3 with options.safe set to true. The same thing happens to the ::before notation.

Here is an explanation of the :after vs. ::after issue http://stackoverflow.com/questions/8980475/after-vs-after

**Comment by TrySound** [comment]
Technically there's no difference between them. And single colon version won't go anywhere. And still you will get one less character in your styles.
