### ISSUE TITLE
Wrapped quotes around font family names are removed

### ISSUE THREAD

**Issue by Olivia101** [ben-eb/cssnano#233]
Any reason why the wrapped quotes around font family names are removed?

code,kbd,pre,samp {
  font-family: Menlo, Monaco,Consolas, "Liberation Mono", "Courier New", monospace;
}

is minified to:

code,kbd,pre,samp {
  font-family: Menlo,Monaco,Consolas,Liberation Mono,Courier New,monospace;
}

The Bootstrap v4 .scss files where minified using cssnano 3.7.3 with options.safe set to true

**Comment by TrySound** [comment]
Because in this case you get two chars less css. Is that a real problem for you?

**Comment by danwhitacre** [comment]
@TrySound What about in the case where I am including css that uses `font-feature-settings: 'liga';`. The quotes are being stripped here incorrectly to produce `font-feature-settings: liga`.

**Comment by danwhitacre** [comment]
Oh I think it has been fixed.

**Comment by TrySound** [comment]
It's only about font and font family. If you found a bug with feature settings then report a new issue please.

**Comment by danwhitacre** [comment]
It seems you guys fixed it 3.x and I need to update my dependency. My mistake.
