### ISSUE TITLE
z-index value changed

### ISSUE THREAD

**Issue by Olivia101** [ben-eb/cssnano#236]
For some reason "z-index: 1030;" was minified to "z-index: 1;"

Minified the .scss files using cssnano 3.7.3 with options.safe set to true

**Comment by ben-eb** [comment]
If `options.safe` is `true` then `z-index` won't be converted. Can you provide a repo that demonstrates this issue?

**Comment by Olivia101** [comment]
I just noticed that was the only z-index property in all the .scss files so "z-index: 1030;" was changed to "z-index: 1" in order to get less chars which is the correct behaviour.

**Comment by ben-eb** [comment]
The `z-index` property will be rebased if you set `options.safe` to `false`.

I'm not sure what the problem is here?
