### ISSUE TITLE
browserslist configuration file is not being used

### ISSUE THREAD

**Issue by thasmo** [ben-eb/cssnano#243]
I've got this gulp task:
```js
return gulp.src('*.{scss,css}')
	.pipe($.sass())
	.pipe($.autoprefixer())
	.pipe($.cssnano())
	.pipe(gulp.dest(path.public.style));
```
I've configured the `browserslist` options using a `browserslist` [configuration file](https://github.com/ai/browserslist#config-file) in the root of the project directory. When `$.autoprefixer()` runs, `autoprefixer` does it's job and adds the configured vendor-prefixes. Afterwards `$.cssnano()` runs and **removes** the vendor-prefixes again, because it apparently does **not** read the `browserslist` file from the project's root directory - I guess.

Is this the intended behavior? For now I had to disable `autoprefixer` in the `cssnano` configuration to keep the vendor-prefixes.

**Comment by ben-eb** [comment]
Hi Thomas,

We don't pass any special settings to autoprefixer in regard to browser support, it should "just work". Not sure why this isn't the case for you?

Anyway, seeing as you already have one autoprefixer configuration then `{autoprefixer: false}` is probably your best solution.

**Comment by thasmo** [comment]
@ben-eb I'm just confused about the autoprefixer optimization then. It says `Removes unnecessary prefixes based on the browsers option. Note that by default, it will not add new prefixes to the CSS file.`.

Where do I set the browsers option and if not set, what default will it use? The default from browserslist?

**Comment by ben-eb** [comment]
Yeah, it will just use the defaults. You can set this by;

```js
{
  autoprefixer: {
    browsers: 'last 2 versions'
  }
}
```

**Comment by thasmo** [comment]
@ben-eb So, why wouldn't the plugin use the browserlist configuration file if it's present? Is there some reason I can't think of?

**Comment by ben-eb** [comment]
I'm not sure exactly.

poke @ai

**Comment by ai** [comment]
Very strange. It should work. Maybe because of `gulp-autoprefixer` instead of `gulp-postcss`? :-(

**Comment by thasmo** [comment]
`gulp-autoprefixer` successfully reads the `browserslist` file and adds the desired prefixes. But afterwards `cssnano` removes them again, because it (probably) doesn't respect or read the `browserslist` file. No idea why tho.

**Comment by ben-eb** [comment]
What happens if you explicitly set the browsers option in cssnano?

**Comment by ai** [comment]
@ben-eb maybe you don’t set `from` option to Autoprefixer?

**Comment by ben-eb** [comment]
Should `from` make a difference?

**Comment by ai** [comment]
@ben-eb yeap, `browserslist` lib uses `from` option to find config file.

**Comment by ben-eb** [comment]
gulp-cssnano does set the `from` option, so I don't know what would be causing this.

**Comment by ai** [comment]
@ben-eb how did you run Autoprefixer in cssnano? Maybe you have some magic and miss `from` option?

**Comment by ben-eb** [comment]
[Same way](https://github.com/ben-eb/cssnano/blob/cda2edbbe54d906be86c157fed5dceabd256e24c/src/index.js#L54) all of the other processors are being loaded; an object of processors which are each [added](https://github.com/ben-eb/cssnano/blob/cda2edbbe54d906be86c157fed5dceabd256e24c/src/index.js#L141) to a new PostCSS instance and returned.

**Comment by ai** [comment]
Strange. @thasmo could you put `console.log` in Autoprefixer’s code. Maybe you have some problems in environment?

**Comment by thasmo** [comment]
Just built a small test-case and it worked. I have to check the build-process at work next week; that's where it's not working. Thanks for the help so far to both of you!
