### ISSUE TITLE
Fill colour in SVG getting compressed unsafely

### ISSUE THREAD

**Issue by passcod** [ben-eb/cssnano#245]
I have an inline SVG in a source file:

```
background-image: url('data:image/svg+xml,<svg
xmlns="http://www.w3.org/2000/svg" width="120" height="32" viewBox="0 0 1200 320">
<path d="M137.189 140V17.17h-36.676L73.871 [snip] 31.832z" fill="rebeccapurple"/></svg>');
```

_(linebreaks added for readability and not part of source)_

This is getting converted, with cssnext, to:

```
background-image: url('data:image/svg+xml,<svg
xmlns="http://www.w3.org/2000/svg" width="120" height="32" viewBox="0 0 1200 320">
<path d="M137.189 140V17.17h-36.676L73.871 [snip] 31.832z" fill="rgb(102,51,153)"/></svg>');
```

Which is still valid SVG. But then cssnano comes along:

```
background-image: url('data:image/svg+xml,<svg
xmlns="http://www.w3.org/2000/svg" width="120" height="32" viewBox="0 0 1200 320">
<path d="M137.189 140V17.17h-36.676L73.871 [snip] 31.832z" fill="#639"/></svg>');
```

Ooops. That should be `%23639`. Having it as a literal `#` breaks the SVG and therefore breaks the build… only in production (I don't run cssnano in dev).

([While `#hex` colour are valid in _SVG_, they're not in _URLs_](https://stackoverflow.com/questions/28588050/how-to-use-a-hex-value-for-svg-in-firefox).)

But, trying to workaround:

Encoding the colour properly (so `fill="%23639"/></svg>`) _then_ causes a further cssnano corruption, because it "optimises" to: `fill='%23639'/%3E%3C/svg%3E`! So this is an unworkaroundable problem.

**Comment by passcod** [comment]
The workaround I'm using is to hardcode the colour as its minimal safe representation, so it doesn't get optimised, so this is not urgent or anything.

**Comment by ben-eb** [comment]
In the meantime you can disable [postcss-svgo](https://github.com/ben-eb/postcss-svgo);

```js
{
  svgo: false
}
```

We should look into url-encoding `#`. Pull requests would be very welcome. 😄
