### ISSUE TITLE
cssnano renames css keyframes to "a"

### ISSUE THREAD

**Issue by breytex** [ben-eb/cssnano#247]
Css nano used in gulp renames
`@-webkit-keyframes toRightFromLeft {`
to
`@-webkit-keyframes a {`

leading to conflicts with css rules defining styles for a link ("a").
All my animations stopt working because of this renaming and I had to stop using css nano.

**Comment by ben-eb** [comment]
Would you be able to share an example of this? As far as I am aware the keyframes identifiers are separate to the identifiers for HTML tags, and I've been running this transform on a few sites without problems.

**Comment by breytex** [comment]
Hey!
Sorry, I am not able to deliver a full working example since I found the bug in a very big project and I am not as-good with gulp to create a quick and small example in-time (yet).

But I am 100% sure that css nano renamed the keyframe name as showed in my #1 post.
After I disabled css nano, everything worked again.

Some more information:
The keyframe css rule was placed in a scss file. In an other scss file, the keyframes where referenced. We use a pipe to put all scss contents together in one big file and then use css nano on the big file with the stated result.

I found the bug when scrolling through the dist css file, my editor (atom) highlighted the new name "a" in red, the color which is used to show that this is a reserved name (like b, li, ul...)

**Comment by ben-eb** [comment]
If you don't want the behaviour you can always disable the [transform](https://github.com/ben-eb/postcss-reduce-idents);

```js
{
  reduceIdents: false
}
```

An example would definitely be useful, I haven't had any problems with this transform thus far. 😄

**Comment by bfricka** [comment]
There's nothing "reserved" about a keyframe "a", but as mentioned you can certainly disable the transform

**Comment by stewones** [comment]
+1 here
the mentioned workaround solves
```
cssnano({
  reduceIdents: false
})
```

**Comment by gavinlynch** [comment]
just got this issue as well. it's still around.

**Comment by os1r1s110** [comment]
Also got this same problem. Proposed workaround is effectively working, but it would be nice to have the option to let minification process keyframes without breaking them.

**Comment by andyjansson** [comment]
How does the issue manifest itself?

**Comment by os1r1s110** [comment]
What do you mean how does it manifest? 
Exactly as described above: 

> Css nano used in gulp renames
@-webkit-keyframes toRightFromLeft {
to
@-webkit-keyframes a {

>

**Comment by sqfbeijing** [comment]
I have the same problem as @breytex.  cssnano change the keyframes '@keyframes g-line-loading' to '@keyframes a'. And   '@keyframes swiper-preloader-spin ' to '@keyframes a'. So  the two animation in the same html are all 'a', and go wrong.

**Comment by impressor615** [comment]
I encountered the same issues!

**Comment by MikeChugunov** [comment]
Same, it won't be a problem with single file probably, but it starts to messing with multiple minified files. 
```js
cssnano({
  reduceIdents: false
})
```
resolves issue

**Comment by manavm1990** [comment]
Yes, I am using: https://daneden.github.io/animate.css/ As part of my **production build only** unless I use 
```
cssnano({
  reduceIdents: false
})
```
it will completely break all of the class names that are defined in the library and no animations will work.

**Comment by vincentbernat** [comment]
I was also hit with this issue. However, in my case, the explanation is quite simple: I am using several CSS files in the same page. If they each contain keyframes, I get conflicting definitions.

**Comment by toobull** [comment]
@vincentbernat I'm the same with you.

**Comment by dyw934854565** [comment]
it will also remove the keyframes not used in a same file. Is there way to prevent?

**Comment by Lakston** [comment]
Just had this happen to me, took me 2 hours to find the culprit, `reduceIdents: false` fixes it but it's not a proper solutions as it defeats the purpose of a minifier...

**Comment by dalyr95** [comment]
Getting this issue as well. I have two separate animations, works fine on page load, then when the chunk with the other animation is loaded it, its keyframe `a` overrides the previous one.

**Comment by thomasclausen** [comment]
I got the a similar problem with a couple of websites where I use [animation.css](https://daneden.github.io/animate.css/). My problem is that in Internet Explorer 11 an element gets a different animation then expected.
All my styles are in a single minified stylesheet, and as far as I can see it's because Internet Explorer doesn't know the difference between keyframes with uppercase and lowercase name - ex. `@keyframes a {}` and  `@keyframes A {}`.

**Comment by yansyjing** [comment]
the same problem

**Comment by andyjansson** [comment]
This optimisation is only enabled in the advanced preset in cssnano 4. If you're using the default preset, this shouldn't be an issue.

**Comment by tkiehne** [comment]
A better fix is to use the string identifier for keyframes: display, e.g.:

```
@-webkit-keyframes 'toRightFromLeft' {...}
...
animation: 'toRightFromLeft'...
```
The names are preserved in the compiled css.

https://www.w3.org/TR/css-animations-1/#typedef-keyframes-name

**Comment by BB-000** [comment]
> A better fix is to use the string identifier for keyframes:

This causes me a sass compile error

Warning: undefined:24:20: @keyframes missing name Use --force to continue.

**Comment by tkiehne** [comment]
Sometime since my comment above, Chrome (on Mac OS X) stopped allowing quotes on animation names.  Now the "better" workaround seems to be to implement the cssnano parameters, but in a more targeted fashion:

```
...
reduceIdents: { keyframes: false}, 
discardUnused: { keyframes: false },
...
```

The animation name comes through unmolested and without quotes while retaining the default reduceIndents behavior for everything else.

**Comment by janwillemvancappellen** [comment]
To only target the keyframes:

`reduceIdents: { keyframes: false}`

**Comment by rcknaman** [comment]
cssnano({ 
  discardUnused: false,
  reduceIdents: false
});
does the trick for me:)
