### ISSUE TITLE
Having the ability to disable all optimisations except a certain set

### ISSUE THREAD

**Issue by crisbeto** [ben-eb/cssnano#248]
At the moment, if you wanted to **only** use `core`, you'd have to maintain a list of optimisations that are enabled by default, and disable each one individually. It would be useful to either have an option that allows you to disable everything except certain optimisations. A couple of ways to approach it could be:

1. Having a flag on each of the options that tells cssnano that it's "important". I'm not too sure how this would work out, though.
2. Exposing a list of all optimisations, allowing the user to loop through them and run some custom logic to disable them. This is probably the easiest to do, but I'm not sure how it would work with the Gulp, Grunt etc. plugins since you'd need both the plugin and cssnano in your dependencies.

**Comment by ben-eb** [comment]
This is going to be resolved in version 4 with presets. For more information see https://github.com/ben-eb/cssnano/issues/88.

Going to close this as 88 is already tracking this issue. 😄
