### ISSUE TITLE
cssnano through postcss-loader (WebPack)

### ISSUE THREAD

**Issue by IngwiePhoenix** [ben-eb/cssnano#25]
I would like to use CSSNano's powers through WebPack...but I just can't get the loader to pick up cssnano.

I tried a variation of calling cssnano as a function or just supplying it inside the return array; like so:

```javascript
    postcss: function(){
        return [
            cssnano()
        ];
    },
```

Would be nice if someone could help me here! :)

**Comment by ben-eb** [comment]
[css-loader](https://github.com/webpack/css-loader) integrates cssnano already. I'm not familiar with postcss-loader. :smile:

**Comment by IngwiePhoenix** [comment]
Oh. o.o That I did not know. Thanks for your response anyway!

postcss-loader picks up custom plugins…and looking at css-loader, it uses a few postcss stuff too.

**Comment by ben-eb** [comment]
:+1:

**Comment by Chris2011** [comment]
> [css-loader](https://github.com/webpack/css-loader) integrates cssnano already. I'm not familiar with postcss-loader. 😄

I read this and I trusted you, but unfortunately this is not correct :D. I tested it right now.

Here you can see the differences between `style-loader, css-loader, sass-loader` to `style-loader, css-loader, postcss-loder, sass-loader`
{code:css}
/* Minimized CSS w/o postcss-loader & w/o cssnano */
body{margin:0;border:1px solid rgba(0,0,0,0.5);font-family:Arial}p{margin:0}
/* Minimized CSS w/ postcss-loader & w/ cssnano */
body{border:1px solid rgba(0,0,0,.5);font-family:Arial}body,p{margin:0}
{code}
