### ISSUE TITLE
Autoprefixer setting should be false by default

### ISSUE THREAD

**Issue by stefan-kern** [ben-eb/cssnano#252]
I lost a good amount of time debugging because i didn't know cssnano was removing IE9 prefixes (-ms-transform). 

Autoprefixer removes features by itself of which it can't know are no longer needed and should therefore also be labelled unsafe in this list: http://cssnano.co/optimisations/#discardcomments.

**Comment by jmarceli** [comment]
I'm having similar problem (with `-ms-transform` prefix) how do you manage to preserve it in output CSS?

**Comment by stefan-kern** [comment]
cssnano currently runs autoprefixer by default (which strips old -ms- prefixes), so you can either disable the autoprexifer plugin completely by setting ```autoprefixer: false``` or give it a browserlist like so:
```js
autoprefixer: {
 browsers: [
    'ie >= 9',
 ]
}
```

i'd would like to mention again that this should not be default behaviour as its not transparent why code is lost.

**Comment by jmarceli** [comment]
Thanks.

**Comment by redaxmedia** [comment]
I suggest to remove the autoprefixer from cssnano according to separation of concerns.

**Comment by tayvano** [comment]
+1

If you are using cssnano, you are most likely also using autoprefixer by default. Having this included adds unnecessary bloat and another thing that leads to debugging issues galore. 

Cssnano is already much slower compiling than the old css minify and the road map should prioritize making these tools as simple and lean and single use as possible.

In addition, removing old prefixes should happen at the scss/less level, not when compiling. It should happen once and from then on autoprefixer should add whatever prefixes you need on compile.

**Comment by corysimmons** [comment]
I believe it doesn't prefix by default anymore.

You can add in prefixing with `--autoprefixer.add`. If you're using an older version I believe you can `--no-autoprefixer`.

Maybe the API for these should be more uniform though? :D

**Comment by ben-eb** [comment]
Resolved in https://github.com/ben-eb/cssnano/releases/tag/v4.0.0-rc.0.
