### ISSUE TITLE
No option to prevent cssnano from converting units

### ISSUE THREAD

**Issue by eplehans** [ben-eb/cssnano#27]
In some cases it would be nice if cssnano wouldn't convert my pixels into points or picas. Being able to disable all unit converting would be a really nice feature.

**Comment by ben-eb** [comment]
Why? All of the CSS absolute measurements are relative to each other and are interchangeable.

http://www.w3.org/TR/css-values-3/#absolute-lengths

**Comment by ben-eb** [comment]
Related: https://github.com/ben-eb/postcss-convert-values/issues/1
