### ISSUE TITLE
Issue with viewport size units

### ISSUE THREAD

**Issue by ThibautNicodeme** [ben-eb/cssnano#273]
I had no issue using the cssnano CLI until I added viewport-based units (vw to be exact) in my CSS file. Suddenly the output becomes blank; and if I comment the lines that use vw, cssnano works once again.

I assume that means those units are not supported by cssnano? Is it possible to update it to support them? The CLI was a really convenient way to minimize my CSS locally and right now I can't use it at all.

**Comment by ben-eb** [comment]
Could you provide some CSS that reproduces the problem, please?

**Comment by ThibautNicodeme** [comment]
I tried again today, and the problem was gone. Apparently what was actually causing the issue was that I left the old pixel values as placeholders while I was tweaking the vw values (so I had lines like `font-size:3.125vw;52.5px;`). Technically unclean code, I know, but it's weird that it worked in browser but made CSSnano fail. Sorry about the false alarm on vw values though.

**Comment by ben-eb** [comment]
Yeah, this invalid CSS would have caused a crash (whereas in browser the unrecognised syntax would have been ignored). We should probably handle these errors better in the CLI.

**Comment by ben-eb** [comment]
@ThibautNicodeme The CLI will now report any errors on stderr;

```css
h1 { font-size:3.125vw;52.5px; }
```

Produces:

```
<css input>:1:24: Unknown word
> 1 | h1 { font-size:3.125vw;52.5px; }
    |                        ^
  2 |
```
