### ISSUE TITLE
JQueryUI comments survive minification

### ISSUE THREAD

**Issue by SilkAndSlug** [ben-eb/cssnano#275]
I downloaded a customised CSS file from JQueryUI, called jquery-ui-1.8.22.custom.css. Each block in the file is commented with multi-line comments with exclaimation marks -- i.e. /*! */ -- which CSSNano does NOT strip, but should.

**Comment by marcobiedermann** [comment]
@SilkAndSlug 

> Note that any special comments marked with ! are kept by default.

http://cssnano.co/optimisations/discardComments

**Comment by ben-eb** [comment]
@marcobiedermann Thanks for handling this one. 👍 

@SilkAndSlug Indeed, you should use the `removeAll` option. It's not done by default because most of the time these comments should be kept with the code due to the way that the code is licensed.

**Comment by SilkAndSlug** [comment]
Dear Future Reader,

How to use the removeAll option in (cssnano-js and) [cssnano-cli](https://github.com/ben-eb/cssnano-cli/issues/3#issuecomment-183632995):

     cssnano --discardComments.removeAll < foo.css > foo.min.css

Yours,
Steve
