### ISSUE TITLE
SVGO Dependency generating errors

### ISSUE THREAD

**Issue by randombitsUK** [ben-eb/cssnano#279]
Hi,

CSS Nano has a dependency on postcss-svgo.

```
"postcss-svgo": "^2.1.1"
```

The latest version of postcss-svgo (2.1.5) is now causing an npm error (node v0.12.7), whereas 2.1.4 appeared to be fine.

The error is:
```
node_modules/cssnano/node_modules/postcss-svgo/node_modules/svgo/plugins/cleanupIDs.js:123
    for (var ID of referencesIDs) {
```

I've logged an issue with postcss-svgo (https://github.com/ben-eb/postcss-svgo/issues/48) but also creating this issue for reference in case anyone else comes across this issue.

**Comment by pmwisdom** [comment]
Seeing the same thing here.

**Comment by parkej60** [comment]
Seeing the same thing from what I believe to be the gulp-cssnano npm package. It has a dependency of "cssnano": "^3.0.0"

**Comment by ben-eb** [comment]
I already responded in https://github.com/ben-eb/postcss-svgo/issues/48, but what might also help is an SVG example that can reproduce this issue.

**Comment by ben-eb** [comment]
svgo 0.7.1 is out so I'm going to close this.
