### ISSUE TITLE
Disable unsafe rules by default

### ISSUE THREAD

**Issue by tlrobinson** [ben-eb/cssnano#28]
I just wasted a bunch of time tracking down a problem caused by cssnano's z-index optimization. You should disable unsafe rules by default, especially for something like z-index optimization which will likely only save a couple characters.

**Comment by ben-eb** [comment]
I've been considering a `safe` option which will act as sugar for wrapping all "unsafe" optimisations. But aggressive compression is turned on by default in projects like clean-css and csso, so I would rather follow this pattern. What is safe for some projects might be unsafe for others.

**Comment by ben-eb** [comment]
The `safe` option is now available since `3.1.0`.

https://github.com/ben-eb/cssnano/commit/a16ed707145f356f850493c655fad99f9dbd9cbf

**Comment by ryngonzalez** [comment]
I think it's probably a good idea to make the `safe` option `true` by default; just spent a good while trying to debug this `z-index` rebasing issue, and I don't think it's worth the hassle for the marginal savings it brings.
