### ISSUE TITLE
Comments are not removed on some conditions

### ISSUE THREAD

**Issue by bisubus** [ben-eb/cssnano#291]
cssnano is used as PostCSS plugin (the chain is reused in Webpack and Gulp tasks). Some chain parts may be conditionally disabled, cssnano is configured to provide minification.

The prefixes are served separately, similarly to [this](https://github.com/postcss/autoprefixer#outdated-prefixes).

This chain

```
postcss([
  autoprefixer({ add: false, browsers: [] }),
  autoprefixer({ browsers: [...] }),
  cssnano({ autoprefixer: false, { removeAll: true } })
]);
```

results in `postcss-discard-comments` being not applied (plugin debugging showed that plugin [factory function](https://github.com/ben-eb/postcss-discard-comments/blob/master/src/index.js#L7) is called but [processing function](https://github.com/ben-eb/postcss-discard-comments/blob/master/src/index.js#L31) isn't. Other cssnano plugins are fine (at least, most of them).

Removing one or both `autoprefixer` from the chain makes comment removal working:

```
postcss([
  autoprefixer({ browsers: [...] }),
  cssnano({ autoprefixer: false, { removeAll: true } })
]);
```

When `postcss-discard-comments` is added to the chain separately, it works:

```
postcss([
  autoprefixer({ add: false, browsers: [] }),
  autoprefixer({ browsers: [...] }),
  cssnano({ autoprefixer: false }),
  discardComments({ removeAll: true })
]);
```

The issue probably duplicates #61, but the resolution (mismatching PostCSS versions) isn't applicable. Package versions are latest stable and are matched (even though NPM 2 is used, `postcss` and plugins are deduped, and `cssnano` requires `postcss`, `autoprefixer` and `postcss-discard-comments`
from root `node_modules`):

node 6.2.2
npm 2.15.11

autoprefixer 6.5.0
cssnano 3.7.6
postcss 5.2.4
postcss-discard-comments 2.0.4

**Comment by ben-eb** [comment]
Possible duplicate of https://github.com/ben-eb/cssnano/issues/90.

**Comment by bisubus** [comment]
@ben-eb Indeed, it seems to be the same case. Not sure how dupe `autoprefixer` is connected to `postcss-discard-comments` but `filterPlugins: false` option helps, thanks.
