### ISSUE TITLE
Convert metadata into the TOML format.

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/cssnano#293]
[This metadata](https://github.com/ben-eb/cssnano/blob/master/metadata.json) is used to build the documentation for cssnano; structurally it's fine, but it's difficult to add new sections (especially of code/long form text) as there's a lot of line-breaking that has to be added manually. I think we would be better served with a language like TOML instead, which has much better multi-line string support.

Here's a sample of how the output should look like:

```toml
[[modules]]
name = "autoprefixer"
shortDescription = "Removes outdated vendor prefixes"

longDescription = """
Removes unnecessary prefixes based on the `browsers` option. Note that *by default*,
**it will not add new prefixes** to the CSS file.
"""

inputExample = """
.box {
    -moz-border-radius: 10px;
    border-radius: 10px;
    display: flex;
}
"""

outputExample = """
.box {
    border-radius: 10px;
    display: flex;
}"""
```

Using a script to do this conversion is absolutely fine by me, so long as the output is close to the above!

Right now, the data is used only for the documentation site, so once the conversion is done you'll need to check that it still works. I think that we need to add the [toml-loader](https://github.com/KyleAMathews/toml-loader) to [this section of the webpack config](https://github.com/ben-eb/cssnano/blob/master/docs/webpack.config.babel.js#L37), and then [update this import statement](https://github.com/ben-eb/cssnano/blob/master/docs/web_modules/app/metadata.js#L4) to point to the new TOML file.

You can verify that it works after this by changing into the `docs` directory and running `npm start`; once the server is running, check a page such as `optimisations/svgo` to ensure that this change worked correctly.

If you have any questions, ask away! 😄

**Comment by jameskolce** [comment]
Hey @ben-eb I'll check this out, I might be able to do it, will let you know!

**Comment by jameskolce** [comment]
Without any changes I'm getting this:
```
ℹ Phenomic is starting 
✔ Development server listening on http://0.0.0.0:3333/ +1.25s
✖ Updated with warnings

⚠ Warning in ./content/blog/new-beginnings.md
Module build failed: Error: Phenomic loader `feed` option has been changed since 0.17.0. The changelog was not mentionning this breaking change. Sorry about that. Please visit https://phenomic.io/docs/usage/feeds/ to know how to migrate (spoiler: it's easy). 
    at Object.loader (./node_modules/phenomic/lib/loader/index.js:47:11)
 @ ./content \.md$ 

⚠ Warning in ./content/blog.md
Module build failed: Error: Phenomic loader `feed` option has been changed since 0.17.0. The changelog was not mentionning this breaking change. Sorry about that. Please visit https://phenomic.io/docs/usage/feeds/ to know how to migrate (spoiler: it's easy). 
    at Object.loader (./node_modules/phenomic/lib/loader/index.js:47:11)
 @ ./content \.md$ 

⚠ Warning in ./content/index.md
Module build failed: Error: Phenomic loader `feed` option has been changed since 0.17.0. The changelog was not mentionning this breaking change. Sorry about that. Please visit https://phenomic.io/docs/usage/feeds/ to know how to migrate (spoiler: it's easy). 
    at Object.loader (./node_modules/phenomic/lib/loader/index.js:47:11)
 @ ./content \.md$ 

⚠ Warning in ./content/404.md
Module build failed: Error: Phenomic loader `feed` option has been changed since 0.17.0. The changelog was not mentionning this breaking change. Sorry about that. Please visit https://phenomic.io/docs/usage/feeds/ to know how to migrate (spoiler: it's easy). 
    at Object.loader (./node_modules/phenomic/lib/loader/index.js:47:11)
 @ ./content \.md$ 

⚠ Warning in ./content/optimisations.md
Module build failed: Error: Phenomic loader `feed` option has been changed since 0.17.0. The changelog was not mentionning this breaking change. Sorry about that. Please visit https://phenomic.io/docs/usage/feeds/ to know how to migrate (spoiler: it's easy). 
    at Object.loader (./node_modules/phenomic/lib/loader/index.js:47:11)
 @ ./content \.md$ 

⚠ Warning in ./content/options.md
Module build failed: Error: Phenomic loader `feed` option has been changed since 0.17.0. The changelog was not mentionning this breaking change. Sorry about that. Please visit https://phenomic.io/docs/usage/feeds/ to know how to migrate (spoiler: it's easy). 
    at Object.loader (./node_modules/phenomic/lib/loader/index.js:47:11)
 @ ./content \.md$ 

⚠ Warning in ./content/usage.md
Module build failed: Error: Phenomic loader `feed` option has been changed since 0.17.0. The changelog was not mentionning this breaking change. Sorry about that. Please visit https://phenomic.io/docs/usage/feeds/ to know how to migrate (spoiler: it's easy). 
    at Object.loader (./node_modules/phenomic/lib/loader/index.js:47:11)
 @ ./content \.md$ 
```

And on the website I get a 404 error. I'll check this out too.

**Comment by jameskolce** [comment]
Okay, I fixed the last one but I'm getting this when visiting any of the pages in optimisations/

![image](https://cloud.githubusercontent.com/assets/2559808/19324877/e0a73652-9080-11e6-87bc-0f0e762facfc.png)

**Comment by ben-eb** [comment]
Hi @jameskolce, thanks for your interest! 😄

I've updated `master` with some fixes for the latest version of Phenomic, can you let me know if this solves the rendering issues? There were some breaking changes about a week ago which I hadn't landed yet, and I didn't realise due to my cached `node_modules`. I've reinstalled from fresh and now don't have any errors. Hopefully you should be able to continue now!

**Comment by jameskolce** [comment]
Awesome, thank you. I'll send a pull request in a moment. Just about to update to macOS Sierra, after that I'll continue :D

**Comment by jameskolce** [comment]
I'm still getting the same last error when accessing `http://localhost:3333/optimisations/autoprefixer`:

![image](https://cloud.githubusercontent.com/assets/2559808/19328993/c32c9384-9093-11e6-82cf-3e01ba9fe1e9.png)

**Comment by ben-eb** [comment]
Strange indeed. Which version of Node are you using?

**Comment by jameskolce** [comment]
6.6.0

**Comment by jameskolce** [comment]
Just updated to v6.8.0, but is the same thing

**Comment by ben-eb** [comment]
Can you try changing https://github.com/ben-eb/cssnano/blob/master/docs/scripts/markdownRenderer.babel.js#L9 to `remark()` and see if that fixes the issue?

**Comment by jameskolce** [comment]
Just changed that, but the problem is still there. I would like to help to find a solution, but I already tried and didn't have any luck :/

**Comment by jameskolce** [comment]
That happens with all the pages inside `optimisations`. Also, the `usage` page stays like this:

![image](https://cloud.githubusercontent.com/assets/2559808/19329717/819f5bf0-9097-11e6-96d5-61756fe36bfc.png)

I don't know if that's related with the current issue.

**Comment by ben-eb** [comment]
Do you have any warnings in the console?

**Comment by jameskolce** [comment]
No, I only get this:

![image](https://cloud.githubusercontent.com/assets/2559808/19329801/f47cc16c-9097-11e6-9419-baeca232c691.png)

**Comment by ben-eb** [comment]
How about the browser console?

**Comment by jameskolce** [comment]
I get this:

![image](https://cloud.githubusercontent.com/assets/2559808/19329894/57aa66cc-9098-11e6-80fc-baaf6ae58069.png)

**Comment by jameskolce** [comment]
This is the content I get when clicking `autoprefixer`:

```
<!doctype html>
  <html>
  <head><meta charset="utf8" /></head>
  <body>
    <div id="phenomic">
      <div
        id="phenomic-DevLoader"
        style="color: red; font: caption; text-align: center; line-height: 100vh; font-size: 2rem;"
      >
        <script>
        window.onerror = function(e) {
          var devLoader = document.querySelector("#phenomic-DevLoader")
          if (devLoader) { devLoader.innerHTML = e.toString() }
          // only need to use this code once
          window.onerror = null
        }
        </script>
      </div>
    </div>
    <script>
    window.__COLLECTION__ = [{"layout":"PageError","route":"404.html","__filename":"404.md","__url":"/404.html","__resourceUrl":"/404.html","__dataUrl":"/404.html.621d497b9b3643e03358f2d161e79b45.json"},{"title":"Blog","layout":"Blog","__filename":"blog.md","__url":"/blog/","__resourceUrl":"/blog/index.html","__dataUrl":"/blog/index.html.a30b6b3f442d75793eb692bcbbf0153b.json"},{"title":"New beginnings","date":"2016-05-10T00:00:00.000Z","layout":"Post","__filename":"blog/new-beginnings.md","__url":"/blog/new-beginnings/","__resourceUrl":"/blog/new-beginnings/index.html","__dataUrl":"/blog/new-beginnings/index.html.3ebaafd83e3dcce7b4088f361ec70d12.json"},{"title":"cssnano: A modular minifier based on the PostCSS ecosystem.","layout":"Homepage","__filename":"index.md","__url":"/","__resourceUrl":"/index.html","__dataUrl":"/index.html.202b9681a6cc37481e5d324e31ca72d4.json"},{"title":"Optimisations","layout":"Optimisations","__filename":"optimisations.md","__url":"/optimisations/","__resourceUrl":"/optimisations/index.html","__dataUrl":"/optimisations/index.html.cdac7070c6c1ece52108a57f1d8df42d.json"},{"title":"Options","layout":"BasicPage","__filename":"options.md","__url":"/options/","__resourceUrl":"/options/index.html","__dataUrl":"/options/index.html.9e889381e5e34ca9f500ae1dc3e30bcf.json"},{"title":"Usage","layout":"Usage","__filename":"usage.md","__url":"/usage/","__resourceUrl":"/usage/index.html","__dataUrl":"/usage/index.html.92e47631cf9a2fbda8cf13637a0a79eb.json"}];
    </script>
    <script src="/phenomic.browser.78499f37cda91c1c243a.js"></script>
  </body>
  </html>
```

**Comment by ben-eb** [comment]
I've been able to reproduce and tracked it down to an old version of `remark`. I've pushed another patch to `master`; hopefully this solves the issue! 😄

**Comment by jameskolce** [comment]
Awesome! Is working now, I'll send the pull request very soon!
