### ISSUE TITLE
safe options not working with post-css cli

### ISSUE THREAD

**Issue by d3sandoval** [ben-eb/cssnano#298]
Hi there,

I've been pulling my hair out trying to make sure that our z-indexes don't get overwritten by cssnano when running it from postcss via the command line.

We are running the following command:
`$APP_ROOT/node_modules/.bin/postcss --use cssnano -c $APP_ROOT/options.json archive.css > archive-test.css`

with the following options.json file:
`{
        "safe": true
}`

According to your [documentation](http://cssnano.co/options/), setting the option "safe" to true will disable, "custom identifier reduction, z-index rebasing, unused at-rule removal & conversion between absolute length values."

It doesn't. In our un-nano'ed css file (archive.css), we have "z-index: 10001;"
Once we run the command, the nano-ified file transforms this into "z-index:1"

Safe needs to work. Is there a way to make sure that our css files are being processed as expected? Thanks.

**Comment by ben-eb** [comment]
Hi,

I think your configuration might be incorrect; using the CLI you should scope the options to each plugin:

```json
{
  "cssnano": {
    "safe": true
  }
}
```

https://github.com/postcss/postcss-cli#--config-c
