### ISSUE TITLE
:matches() issue

### ISSUE THREAD

**Issue by stevenvachon** [ben-eb/cssnano#299]
I'd noticed an issue with my CSS containing `:matches()` which don't work in Firefox. I can't find the exact plugin that performs this transformation, but I'm positive that it's cssnano because once removing it from my build script, all instances of `:matches()` disappeared.

**Comment by stevenvachon** [comment]
The issue might be caused by caniuse.com stating that `:matches()` *is* supported in Firefox, which is not true. It supports `:any()`.

**Comment by ben-eb** [comment]
Can you provide a minimal test case, please?

**Comment by stevenvachon** [comment]
Sorry for wasting your time and thank you for the quick response. It's an issue with another plugin.
