### ISSUE TITLE
$ trouble

### ISSUE THREAD

**Issue by TrySound** [ben-eb/cssnano#30]
```css
.a:after {
	content: '$';
}
```
with defaults compiles to
```css
.a:after{content:'}
```

**Comment by TrySound** [comment]
Fast fix is replacing with unicode char.

**Comment by ben-eb** [comment]
I'm not sure where this is originating from. Having a look now.

**Comment by TrySound** [comment]
@ben-eb Found this behaivor in `postcss-normalize-url`
