### ISSUE TITLE
`font-family` value mangled

### ISSUE THREAD

**Issue by dustinhorton** [ben-eb/cssnano#31]
This may belong in https://github.com/ben-eb/postcss-font-family, but couldn't be sure.

I'm using the following fonts, which names get mangled when piping through cssnano:

| CSS               | cssnano           |
|-------------------|-------------------|
| FF Din Pro        | Din FF Pro        |
| FF Din Pro Medium | FF Medium Din Pro |
etc.

**Comment by ben-eb** [comment]
That's weird. Will investigate. :smiley:

**Comment by ben-eb** [comment]
Resolved in postcss-font-family@1.1.1.

**Comment by dustinhorton** [comment]
Thanks for looking into it.

Mind clarifying how I can disable font family optimization? I'm using cssnano via Grunt & Gulp within a PostCSS task.

**Comment by ben-eb** [comment]
Sure. Just set `fonts` to false in your config object.

http://cssnano.co/options/
