### ISSUE TITLE
Npm Script giving ENOENT error 

### ISSUE THREAD

**Issue by anoopd** [ben-eb/cssnano#311]
Was trying to use cssnano from npm scripts . Here is my package.json 

```
{
  "name": "js",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "build:css": "node-sass src/styles/*.scss >  dist/styles/main.css ",
    "build:css1": "cssnano < main.css > main.min.css",
    "build": "browserify js/script.js -o js/bundle.js",
    "bs": "browser-sync start --proxy 'localhost/js' --files './'"
  },
  "dependencies": {
    "browser-sync": "^2.18.2",
    "browserify": "^13.1.1",
    "cssnano": "^3.8.1",
    "cssnano-cli": "^1.0.5",
    "jquery": "^3.1.1",
    "node-sass": "^3.13.0"
  }
}
```

When i try running `npm run build:css1` it is giving the following error , can somebody help with  what went wrong ?

```
14 verbose stack Error: js@1.0.0 build:css1: `cssnano < main.css > main.min.css`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/anoopd/.npm-packages/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/anoopd/.npm-packages/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid js@1.0.0
16 verbose cwd /Users/anoopd/Sites/project
17 error Darwin 15.6.0
18 error argv "/usr/local/Cellar/node/6.9.1/bin/node" "/Users/anoopd/.npm-packages/bin/npm" "run" "build:css1"
19 error node v6.9.1
20 error npm  v4.0.2
21 error code ELIFECYCLE
22 error js@1.0.0 build:css1: `cssnano < main.css > main.min.css`
22 error Exit status 1
23 error Failed at the js@1.0.0 build:css1 script 'cssnano < main.css > main.min.css'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the js package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cssnano < main.css > main.min.css
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs js
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls js
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ben-eb** [comment]
Hi @anoopd,

I think the path to the CSS file doesn't exist, you probably want to be using `dist/styles/main.css` as an input, not `main.css`.

Hope this helps.

**Comment by anoopd** [comment]
Hi Ben,
                Thank you so much for the reply . Sorry that i did'nt made it clear . I tried with the whole path first , when i got the error i thought it was something with the relative absolute directory structure , so i just copied the main.css to the base folder and experimented with the current script and then i got the error which i posted here . A blank main.min.css is created too .

**Comment by ben-eb** [comment]
Hi @anoopd,

Is there anything else to the error? Perhaps some CSS I can reproduce the issue with?

**Comment by anoopd** [comment]
hi ben 
           The main.css file in the base( parent) folder have  
`* {
margin:0;
padding:0
}`

once i run the `npm run build:css1`  a new file with name main.min.css is produced but it is a blank one .

**Comment by anoopd** [comment]
`npm run build:css1

> js@1.0.0 build:css1 /Users/anoopd/Sites/project
> cssnano < main.css > main.min.css

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/anoopd/Sites/project/node_modules/svgo/lib/svgo/../../.svgo.yml'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at module.exports (/Users/anoopd/Sites/project/node_modules/svgo/lib/svgo/config.js:31:48)
    at new module.exports (/Users/anoopd/Sites/project/node_modules/svgo/lib/svgo.js:21:19)
    at /Users/anoopd/Sites/project/node_modules/postcss-svgo/dist/index.js:91:16
    at Object.creator [as postcssSvgo] (/Users/anoopd/Sites/project/node_modules/postcss/lib/postcss.js:150:35)
    at /Users/anoopd/Sites/project/node_modules/cssnano/dist/index.js:283:40
    at Array.forEach (native)
    at /Users/anoopd/Sites/project/node_modules/cssnano/dist/index.js:270:29

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.9.1/bin/node" "/Users/anoopd/.npm-packages/bin/npm" "run" "build:css1"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! js@1.0.0 build:css1: `cssnano < main.css > main.min.css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the js@1.0.0 build:css1 script 'cssnano < main.css > main.min.css'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cssnano < main.css > main.min.css
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls js
npm ERR! There is likely additional logging output above.
`

**Comment by ben-eb** [comment]
Hi @anoopd,

I'm not sure exactly, it seems like the svgo dependency hasn't been installed correctly. Perhaps you can try reinstalling your `node_modules` and try again?

**Comment by helfi92** [comment]
@anoopd were you able to resolve this issue?

**Comment by anoopd** [comment]
@helfi92  i ran npm rebuild node-sass  and it just worked

**Comment by helfi92** [comment]
@anoopd thanks. A simple `rm -rf node_modules/ && npm install` fixed my issue.
