### ISSUE TITLE
Inline `defined`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [ben-eb/cssnano#312]
It's a 4KB dependency used [once](https://github.com/ben-eb/cssnano/blob/0c0405609ce683e2ea5605ccb5349fc9c784b84d/src/index.js#L150).  I can submit a PR if you would like.

**Comment by ben-eb** [comment]
Hi @wtgtybhertgeghgtwtg,

I'm going to do a proper review of utilities for v4 so we can decide on if we can use them in more modules (or drop them completely). My general thinking with relying on other's code is that it's about containing complexity, even though `defined`'s functionality is very straightforward, it's one less thing that I have to think about/write unit tests for.

I'm going to close this issue in favour of https://github.com/ben-eb/cssnano/issues/95.
