### ISSUE TITLE
A way to remove ALL comments using the cli tool?

### ISSUE THREAD

**Issue by cmelone** [ben-eb/cssnano#314]
In gulp, I currently use this to remove all the comments:

```javascript
{
  discardComments: {
    removeAll: true;
  }
}
```

I don't see a way to do this through the command line, is this possible?

**Comment by ben-eb** [comment]
Hi @cmelone,

It's possible right now; I'd like a config file option to make this better from the command line but for now, see this issue:

https://github.com/ben-eb/cssnano-cli/issues/3#issuecomment-183632995
