### ISSUE TITLE
border-width problem

### ISSUE THREAD

**Issue by mstijak** [ben-eb/cssnano#328]
I noticed a small problem.
```
border-left-width: 0;
border-right-width: 0;
border-bottom-width: 2px;
border-top-width: 0;
```
is optimized into
```
border: 0;
border-bottom-width: 2px;
```

The problem is that `border:0` also affects `border-style` so this optimization is not safe. 
I think that the correct optimization would be:
```
border-width: 0;
border-bottom-width: 2px;
```
Please advise if this is a bug or if there is a workaround. 
I tried passing `safe: true`, but it didn't help.

**Comment by ben-eb** [comment]
Hi @mstijak,

Yep, this is a known issue. For now you can turn this module off by using `{mergeLonghand: false}`, there's also an issue you can track whilst waiting for a resolution: https://github.com/ben-eb/postcss-merge-longhand/issues/21

**Comment by mstijak** [comment]
@ben-eb: Thanks for the info. I'll close the issue since it's an exact duplicate.
