### ISSUE TITLE
Minification breaks '@media not all ...' style media queries

### ISSUE THREAD

**Issue by alvaroc1** [ben-eb/cssnano#329]
Note the use of "not all and ..."

```bash
$ echo "@media not all and (min-width: 768px) {display: none}" | cssnano --safe
@media not (min-width:768px){display:none}
```

The valid line 
```
@media not all and (min-width: 768px) ...
``` 
gets collapsed to the invalid line 
```
@media not (min-width: 768px)...
```

That makes the @media query not work (tested on chrome).

Same result with and without the `--safe` flag.

As a workaround, instead of "not all" i can use "not screen", which doesn't get collapsed.

Version: cssnano v3.9.1 (cli v1.0.5)

For reference: 
http://stackoverflow.com/questions/36494294/not-max-width-512px-not-working

**Comment by ben-eb** [comment]
Thanks for the report, this has now been resolved in `postcss-minify-params@1.2.2`. 👍
