### ISSUE TITLE
Wilcard hack break other properties

### ISSUE THREAD

**Issue by efusien** [ben-eb/cssnano#33]
Hi,
I tried to minify the following code and the output is not as expected.
In the first rule, the wilcard (* hack) for zoom property seems to generate wilcard for other properties in other rules. But not all rules.

.classA {
  *zoom: 1;
}
.classB {
  box-sizing: border-box;
  position: relative;
  min-height: 100%;
}
.classC {
  box-sizing: border-box;
  position: relative;
}
.classD {
  box-sizing: border-box;
  position: relative;
}

Output :
.classA{*zoom:1}.classB{min-height:100%}.classB,.classC{*box-sizing:border-box;*position:relative}.D{box-sizing:border-box;position:relative}

We see new wilcards on *box-sizing and *position. But only for .classB and .classC.
If we remove the wilcard, all is ok.
Plus, I can't explain why .classD is not merged in the same selector as .classB and .classC.

**Comment by ben-eb** [comment]
Looks like a bug with https://github.com/ben-eb/postcss-merge-rules, which can be disabled with `options.merge` (`cssnano --no-merge` on the CLI)

Please track the issue here: https://github.com/ben-eb/postcss-merge-rules/issues/5
