### ISSUE TITLE
Removing comments only works on recompile (postcss)

### ISSUE THREAD

**Issue by X-Tender** [ben-eb/cssnano#339]
I don't know if it is a postCSS Issue or a cssnano Issue, I just try it here first.
I ahve the following setting for cssnano in my postcss.json config:

```
cssnano: {
	safe: true,
	mergeRules: false,
	browsers: [],
	discardComments: {
        removeAll: true,
    },
},
```
when I run postcss with `watch: true` the initial process contains the comments. When I make a change on my css src files it run again and the comments are not included.

That's pretty anoying becasue I cant run it without watching just to make a production build for example where cssnano is enabled. In Devmode I usualy don't nanofy the css.

**Comment by ben-eb** [comment]
Hi @X-Tender,

Perhaps it is this issue? https://github.com/ben-eb/cssnano/issues/90#issuecomment-191994202

**Comment by X-Tender** [comment]
Yes, that solves it.
Thanks.
