### ISSUE TITLE
Missing line in "javascript" and "javascript (postcss)" usage snippets

### ISSUE THREAD

**Issue by steveharrison** [ben-eb/cssnano#341]
Your code snippets for http://cssnano.co/usage/#javascript and http://cssnano.co/usage/#javascript-postcss are missing the line to read the file and hence the `css` variable is not defined.

Can you please add something along the lines of `var css = fs.readFileSync('css/my-file.css', 'utf8').toString();` so the snippet works as is?

**Comment by ben-eb** [comment]
I think a better thing to do would be to optimise for the lowest common denominator - the `console` - and keep the `css` in the snippet. This seems like low hanging fruit so I'll accept a pull request that changes the `fs` calls to `console.log` and includes a small CSS snippet; `h1 { color: blue }` or something along those lines.

https://github.com/ben-eb/cssnano/blob/1c6c36cb143e36c3f4634df1075cfbf501cee694/metadata.toml#L846-L882

**Comment by ben-eb** [comment]
I've rewritten the documentation so this doesn't apply anymore - there is a `quickstart.js` file bundled with cssnano that is a good starting point for JS usage.
