### ISSUE TITLE
mergeRules - Duplicate selector

### ISSUE THREAD

**Issue by GuillaumeG22** [ben-eb/cssnano#347]
Hello,

I use cssnano with PostCSS width Gulp.

On my personal website (https://guillaume.germain.bzh/), I have duplicate selectors.

Some examples (https://guillaume.germain.bzh/css/main.css):
-  a
- .btn
- body 

Originally, I have 3 "body" selectors. Why the 2 remaining selectors are not grouped ? 

Thanks,
Guillaume

**Comment by soluml** [comment]
Ran into a similar issue.  I have mergeRules turned on but when I process the following string it fails to merge the selectors:

`.A{color:blue}.B{font-weight:700}.B{font-weight:700}.C{font-weight:400}`

**Comment by Jos512** [comment]
Same issue happens with `mergeRules` and the `background-image` property, which, unfortunately, is often a long string and adds a lot of redundant CSS to the file. (In my case, there are dozens of duplicate rules _after_ optimising.)

For a quick example, this CSS:

~~~css
.sp-facebook {
  background-image: url(/static/sprite-b83caa4a9c.png);
  background-position: -95px -45px;
  width: 45px;
  height: 45px;
}
.sp-googleplus {
  background-image: url(/static/sprite-b83caa4a9c.png);
  background-position: 0px -50px;
  width: 45px;
  height: 45px;
}
.sp-linkedin {
  background-image: url(/static/sprite-b83caa4a9c.png);
  background-position: -95px 0px;
  width: 45px;
  height: 45px;
}
.sp-twitter {
  background-image: url(/static/sprite-b83caa4a9c.png);
  background-position: -45px -50px;
  width: 45px;
  height: 45px;
}
~~~

Is minified to:

~~~css
.sp-facebook{
  background-position:-95px -45px;
}
.sp-facebook,.sp-googleplus{
  background-image:url(/static/sprite-b83caa4a9c.png);
  width:45px;
  height:45px;
}
.sp-googleplus{
  background-position:0 -50px;
}
.sp-linkedin{
  background-position:-95px 0;
}
.sp-linkedin,.sp-twitter{
  background-image:url(/static/sprite-b83caa4a9c.png);
  width:45px;
  height:45px;
}
.sp-twitter{
  background-position:-45px -50px;
}
~~~
(`mergeRules` on, but `core` off to keep the readability -- although the issue also happens with `core` on, for that matter.)

I would expect that the `mergeRules` optimisation result in:

~~~css
.sp-facebook,
.sp-googleplus,
.sp-linkedin,
.sp-twitter {
    background-image: url(/static/sprite-b83caa4a9c.png);
    width: 45px;
    height: 45px;
}
.sp-facebook {
  background-position: -95px -45px;
}
.sp-googleplus {
  background-position: 0px -50px;
}
.sp-linkedin {
  background-position: -95px 0px;
}
.sp-twitter {
  background-position: -45px -50px;
}
~~~

**Comment by GuillaumeG22** [comment]
I still get the same problem with version 3.10.0

**Comment by andyjansson** [comment]
It's on the TODO list.

**Comment by chriseppstein** [comment]
The "optimized" output requested is actually larger after compression. (172 bytes for the original, 187 bytes for the proposed output) The only way to make this kind of optimization work out is to generate new selectors that are highly compressible, if you duplicate the authored selector idents, it causes more bloat.

https://github.com/ben-eb/cssnano/issues/424 for more information
