### ISSUE TITLE
grunt usage example is broken

### ISSUE THREAD

**Issue by LordPachelbel** [ben-eb/cssnano#348]
The comma between `options` and `dist` is missing. So this code
```
    options: {
      sourcemap: true
    }
    dist: {
      files: {
        'dist/app.css': 'src/app.css'
      }
    }
```
should be
```
    options: {
      sourcemap: true
    },
    dist: {
      files: {
        'dist/app.css': 'src/app.css'
      }
    }
```

**Comment by ben-eb** [comment]
Hi @LordPachelbel,

Yeah, that's an issue. Would you like to send a pull request to fix this? It's this line: https://github.com/ben-eb/cssnano/blob/master/metadata.toml#L815
