### ISSUE TITLE
remove empty properties

### ISSUE THREAD

**Issue by stevenvachon** [ben-eb/cssnano#352]
```css
selector {
  propertyA: value;
  propertyB: ;
}
```
should reduce to:
```css
selector {
  propertyA: value;
}
```

**Comment by ben-eb** [comment]
Can you test support before opening issues in future, please? This is already handled via https://github.com/ben-eb/postcss-discard-empty. 😉

**Comment by stevenvachon** [comment]
I'd not tested it directly, but my build increased by 1 byte when I filled in a property's value, which was previously empty. If the property were removed, it'd have increased by more.
