### ISSUE TITLE
Add an option to create a file.min.css files instead of replacing original one

### ISSUE THREAD

**Issue by SuperPat45** [ben-eb/cssnano#354]
Hi,

I execute postcss from a Java Ant compilation task on a directory containing many CSS files.
`postcss -c /src/postcss.js -d /css /css/*.css`

With this postcss.js:
```
module.exports = {
  use: [
    'postcss-flexbugs-fixes',
    'autoprefixer',
    'cssnano'
  ],
  autoprefixer: {
    browsers: [
      'Chrome >= 35',
      'Edge >= 12',
      'Explorer >= 10',
      'iOS >= 6',
      'Safari >= 6',
      'Android 2.3',
      'Android >= 4',
      'Opera >= 15'
    ]
  },
  cssnano : {
      safe: true,
      sourcemap: true
  }
}
```
I need to keep the original CSS files.

Can you add an option for css nano minimify original files.css into files.min.css in the same directory instead of replacing original one?

**Comment by ben-eb** [comment]
Hi @SuperPat45,

This seems like more of an issue with your PostCSS runner than cssnano itself; this module does no writing to the filesystem. If you would like separate `*.min.css` files you could try setting up a different task to compress the files:

```js
// /src/postcss.js

module.exports = {
  use: [
    'postcss-flexbugs-fixes',
    'autoprefixer'
  ],
  autoprefixer: {
    browsers: [
      'Chrome >= 35',
      'Edge >= 12',
      'Explorer >= 10',
      'iOS >= 6',
      'Safari >= 6',
      'Android 2.3',
      'Android >= 4',
      'Opera >= 15'
    ]
  }
}
```

```js
// /src/minify.js
module.exports = {
  use: [
    'cssnano'
  ],
  cssnano : {
      safe: true,
      sourcemap: true
  }
}
```

And then run this configuration on the files after the first postcss-cli pass.

Hope this helps!
