### ISSUE TITLE
Feature Suggestion: discardDuplicates for non-exact duplicates?

### ISSUE THREAD

**Issue by soluml** [ben-eb/cssnano#356]
While probably not a feature you'd want in most cases, it can be useful to eliminate duplicate properties for stylesheets that make use of preprocessor features like `@extend`.

**Comment by ben-eb** [comment]
Hi @soluml,

Is this the same thing as https://github.com/ben-eb/postcss-discard-duplicates/issues/1? If not can you post an example?

**Comment by soluml** [comment]
It is the same and is literally the first issue so I'm not sure how I missed it.  Thanks!
