### ISSUE TITLE
why remove -webkit-box-orient property?

### ISSUE THREAD

**Issue by warwr1ck** [ben-eb/cssnano#357]
i use ```vue-cli``` to build my vue project.yesterday i found the property ```-webkit-box-orient``` was removed,while ```box-orient``` was still there.
i don't know why.

**Comment by ben-eb** [comment]
Hi @warwr1ck,

This is a duplicate of https://github.com/ben-eb/cssnano/issues/252 - working on making this better in the coming months. 👍

**Comment by ZhangPingFan** [comment]
@warwr1ck How did you solve the problem? I met this too

**Comment by ZhangPingFan** [comment]
@warwr1ck How did u solve this problem? I meet this now

**Comment by warwr1ck** [comment]
just remove the postcss config in vue-loader's config

**Comment by ZhangPingFan** [comment]
thank u. I found it also works by adding {autoprefixer: false} to the optimize-css-assets-webpack-plugin.

**Comment by rockallite** [comment]
Add the following option to prevent autoprefixer from removing prefixes (for cssnano v3 only):

    {
      autoprefixer: {
        remove: false
      }
    }

Then `-webkit-box-orient` will be preserved.

**Comment by minchangyong** [comment]
// eslint-disable-next-line
/* autoprefixer: off */
-webkit-box-orient: vertical;
/* autoprefixer: on */

**Comment by Mrsosann** [comment]
> // eslint-disable-next-line
> /* autoprefixer: off /
> -webkit-box-orient: vertical;
> / autoprefixer: on */
> 这个方法真心解决问题。

加到 style 里？注释调不生效啊

**Comment by suzyvivi** [comment]
> > // eslint-disable-next-line
> > /* autoprefixer: off /
> > -webkit-box-orient: vertical;
> > / autoprefixer: on */
> > 这个方法真心解决问题。
> 
> 加到 style 里？注释调不生效啊

```
// eslint-disable-next-line
/* autoprefixer: off */
-webkit-box-orient: vertical;
/* autoprefixer: on */
```

add ` * ` , it works.  hahaha~

**Comment by FanJfly** [comment]
no warning when compiling like this also can work:
/* autoprefixer: ignore next */
-webkit-box-orient: vertical;

**Comment by minchangyong** [comment]
all right
















At 2020-04-20 11:46:24, "佐菲" <notifications@github.com> wrote:

no warning when compiling like this also can work:
/* autoprefixer: ignore next */
-webkit-box-orient: vertical;

**Comment by dgknca** [comment]
```js
pipe(
      cssnano({
        autoprefixer: {
          remove: false
        }
      })
    )
```
