### ISSUE TITLE
Default transforms for version 4.

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/cssnano#358]
I'm currently working on version 4 and I'd like to get some community feedback on what transforms we should enable by default. As you may or may not be aware, I'd like to move from being aggressive by default to safe, deprecating the `safe` option. I think it's important to provide aggressive transforms but give people information on when they are correct to use; aggressive transforms are definitely not one-size-fits-all.

My current thinking is along the following lines;

| module | v3 | v4 |
| - | - | - |
| autoprefixer | yes | no |
| postcss-calc | yes | yes |
| postcss-colormin | yes | yes |
| postcss-convert-values | yes | yes |
| postcss-discard-comments | yes | yes |
| postcss-discard-duplicates | yes | yes |
| postcss-discard-empty | yes | yes |
| postcss-discard-overridden | yes | yes |
| postcss-discard-unused | yes | no |
| postcss-filter-plugins | yes | no |
| postcss-merge-idents | yes | no |
| postcss-merge-longhand | yes | yes |
| postcss-merge-rules | yes | yes |
| postcss-minify-font-values | yes | yes |
| postcss-minify-gradients | yes | yes |
| postcss-minify-params | yes | yes |
| postcss-minify-selectors | yes | yes |
| postcss-normalize-charset | yes | yes |
| postcss-normalize-url | yes | no |
| postcss-ordered-values | yes | yes |
| postcss-reduce-idents | yes | no |
| postcss-reduce-initial | yes | yes |
| postcss-reduce-transforms | yes | yes |
| postcss-svgo | yes | yes |
| postcss-unique-selectors | yes | yes |
| postcss-zindex | yes | no |

This is consistent with css-loader's default configuration: https://github.com/webpack-contrib/css-loader/blob/46ebca3dd9cf0fa6c90bb68cd04e4e7158ad3f9d/lib/processCss.js#L183

**Comment by andyjansson** [comment]
Seems to me like a sane set of defaults. I'm thinking that we can also expose a more aggressive (read: unsafe) set of configuration for those looking to produce the smallest stylesheet possible, e.g.:

```js
cssnano.process(css, cssnano.config.aggressive).then(result => {
  // ...
});
```

**Comment by michael-ciniawsky** [comment]
How will options look like in v4 ?

```js
cssnano.process(css) // safe => no options
cssnano.process(css, { autoprefixer: true || {}, ...unsafe }) // unsafe => options
```
?

**Comment by sylvainpolletvillard** [comment]
I like the "safe by default" approach. Can you give details about why disable postcss-normalize-url ?

**Comment by ben-eb** [comment]
@andyjansson @michael-ciniawsky I'd like to do presets, such as ESLint or Babel. So cssnano will have no options internally, instead we will delegate to the preset - which will be loaded via https://github.com/davidtheclark/cosmiconfig (format not yet decided). That also goes for exposing options objects, something I don't really want to do because it means shipping transforms that people might not use.

@sylvainpolletvillard I need some feedback from webpack on why this is turned off, my guess is because it used to remove the `www` prefix in the default configuration. So it will probably make it to the default preset but it'll be limited to how it's configured in v3's current safe mode. https://github.com/ben-eb/cssnano/blob/64a25c633e227eb4842cf0f3a0875815ea412d54/src/index.js#L113-L115

**Comment by michael-ciniawsky** [comment]
@ben-eb How will a preset look like? :)

**Comment by ben-eb** [comment]
@michael-ciniawsky I might need feedback on this separately, going to try a few things first. 😄

**Comment by papandreou** [comment]
Very much in favor of this. After a lot of trial-and-error we've ended up with this config in assetgraph:

```js
{
    svgo: false, // Off because we run svgo on all SVGs in a separate pass, including non-inline ones
    safe: true,
    normalizeUrl: false,
    mergeLonghand: false,
    autoprefixer: false,
    discardComments: {
        remove: function (comment) {
            return !(/@preserve|@license|[@#]\s*sourceURL|[#@]\s*sourceMappingURL|^!/).test(comment);
        }
    }
}
```

It sounds like you're on your way to turn off all those troublemakers by default, except `postcss-merge-longhand`, which should be safe as of 3.0.0. I think that would improve the out-of-the-box experience greatly!

**Comment by ben-eb** [comment]
Quick update, after talking with @papandreou I've decided to set the `stripWWW` option from postcss-normalize-url to `false` by default instead, so now it will only do safe transforms (such as normalizing quotes, directory traversal etc). Therefore we can keep this inside the default preset. 😄

**Comment by ben-eb** [comment]
Resolved in https://github.com/ben-eb/cssnano/releases/tag/v4.0.0-rc.0.
