### ISSUE TITLE
Overeager color reduction in text.

### ISSUE THREAD

**Issue by remy-luisant** [ben-eb/cssnano#359]
h2:before{content:"black"} is reduced to h2:before{content:"#000"}.

I'm a mathematician, not a web developer, but I'd expect the text to be left alone.

Not a major issue by itself, but may crop up elsewhere, in different contexts where words that look like colors may be used. Probably not a high-priority fix at any rate.

**Comment by ben-eb** [comment]
Good catch, thanks! 👍

This is actually fixed locally (due to my postcss-colormin rewrite), however it's not ready for release just yet; it will be in the next major version.

**Comment by jeffijoe** [comment]
I think this is related to an issue I am having where:

```
.button.is-white {}
```

is transformed to

```
.button.is-#fff {}
```

**Comment by remy-luisant** [comment]
Seems like it may be a parse error? I had a conversation about this with the CSSO maintainer, just a tiny while back. Minus is apparently a legal part of identifiers, but here it seems like maybe cssnano does not include it as a valid character and splits the two?

**Comment by jeffijoe** [comment]
In my case this only occurs when `sass-loader` is in production-mode, but that is unrelated to this module. 😄

**Comment by Nirazul** [comment]
I've just stumbled upon this issue. In the meantime you can append a zero-width joiner preventing cssnano from being overeager:

```css
::before{
    content: "black\200C"
}
```

[Glyphs Article from CSS Tricks](https://css-tricks.com/snippets/html/glyphs/#article-header-id-6)
