### ISSUE TITLE
destructive attribute selector minification

### ISSUE THREAD

**Issue by danprince** [ben-eb/cssnano#360]
Tracing down a strange CSS bug from a busted Webpack build using the `-p` flag. Looks like cssnano attempts to minify attribute selectors by removing unnecessary quotes.

```scss
[data-foo="bar"] { ... }
// becomes
[data-foo=bar] { ... }
```

However, this breaks any code that differentiates between an empty and non-empty attribute values.

```scss
// non-empty styles
[data-foo] { ... }

// empty styles
[data-foo=""] { ... }
```

These selectors are minified as:

```scss
// non-empty styles
[data-foo] { ... }

// empty styles
[data-foo=] { ... }
```

The `[data-foo=]` selector matches both empty and non-empty attribute values, whereas `[data-foo=""` only matches empty ones.

However, after a quick look at the code in [`lib/canUnquote.js`][1], it looks like it handles this case. I'm not sure why this would happen.

Looks like `webpack@1.x` → `css-loader@0.25.0` → `cssnano@3.8.0` → `postcss-minify-selectors@2.0.6`.

The `postcss-minify-selectors@2.0.6` release [didn't include the check for empty attributes][2].

For anyone else that runs into this issue, Webpack 1.x is deprecated now and although Webpack 2 still uses `css-loader@0.25.0`, hopefully they'll bump that version in a future release.

[1]: https://github.com/ben-eb/postcss-minify-selectors/blob/master/src/lib/canUnquote.js#L13-L15
[2]: https://github.com/ben-eb/postcss-minify-selectors/blob/5095c6e45f7a6b31d56578414b11001760fc75bc/src/lib/canUnquote.js

**Comment by ben-eb** [comment]
For anyone approaching this issue still, please update your dependencies. We fixed this in November last year! 😄 

https://github.com/ben-eb/postcss-minify-selectors/commit/fc5a2a852a53e96014288ce6232bd85e60c92a5b
