### ISSUE TITLE
URL with space gets unquoted

### ISSUE THREAD

**Issue by huan086** [ben-eb/cssnano#362]
When normalizeUrl is enabled, it converts

`url("/folder/name with space.png")`

into

`url(/folder/name with space.png)`

which causes the image not to load

**Comment by ben-eb** [comment]
Hi @huan086,

I think it might be something else in your environment because I can't reproduce this standalone.

```
[~] $ cssnano -v
cssnano v3.10.0 (cli v1.0.5)
[~] $ cssnano
h1 { background: url("/folder/name with space.png") }
h1{background:url("/folder/name with space.png")}[~] $ 
```

**Comment by huan086** [comment]
You are right. It's due to css-loader, not cssnano https://github.com/webpack-contrib/css-loader/issues/410
