### ISSUE TITLE
mergeRules removes my top: 3px :(

### ISSUE THREAD

**Issue by IIIu6ko** [ben-eb/cssnano#363]
Why is this happening?

![- -8](https://cloud.githubusercontent.com/assets/20703084/25351455/663fac42-2931-11e7-8fdc-3b629d33ab72.png)

**Comment by ben-eb** [comment]
Hi @IIIu6ko,

Would you be able to provide a minimal amount of CSS that can reproduce the problem?

**Comment by IIIu6ko** [comment]
@ben-eb If [mergeRules](http://cssnano.co/optimisations/mergeRules/): false, then everything is fine.
But if you do not disconnect it, it removes the top: 3px from the logo__stars class. 
In the screenshots above, I showed everything. I do not know how to explain it better.

mergeRules: false
.logo__stars{position:absolute;top:3px;right:0}

mergeRules: true
.logo__stars{position:absolute;right:0}

Where does the top disappear: 3px? In the code there is no second class .logo__stars.

**Comment by andyjansson** [comment]
@IIIu6ko I tried to reproduce the problem you're having, but to no avail. Are you still experiencing the issue? If so, could you produce a minimal configuration which reproduces the problem?

**Comment by andyjansson** [comment]
I'm closing this for now. If a snippet is posted demonstrating the problem I'll reopen the issue again.
