### ISSUE TITLE
sourcemap url missed

### ISSUE THREAD

**Issue by tangshuang** [ben-eb/cssnano#367]
In my case, I use:

```
discardComments: false,
```

Other comments are kept. However, the sourcemap url at the end of the css file disappeared.

```
/*# sourceMappingURL=main.3c8bd9cc.css.map*/
```

What should I to keep my sourcemap url, please?

**Comment by evilebottnawi** [comment]
@tangshuang which build tool? `webpack`, if yes your should disable source map using `webpack.config.js`
