### ISSUE TITLE
Documentation: Detailed Usage

### ISSUE THREAD

**Issue by tomciopp** [ben-eb/cssnano#369]
Right now in the docs there is no way to understand how to configure this tool.

What I would expect in the (optimizations)[http://cssnano.co/optimisations] section are the default configuration options listed and then for each individual plugin I would expect a section on the different configuration options that it accepts. When I read the documentation my reaction was this tool looks like it does what I need it to do, but it does not tell me how I can do it.

I would expect the documentation to contain a line like: 

Here is the default configuration: 

{
  autoprefixer: { add: true },
  ....
}

 and then for each component you would have a section on the options it takes and what the defaults are.

For example if you visit this page, http://cssnano.co/optimisations/discardDuplicates/ it shows you that we can discardDuplicates, but it doesn't tell you if that is enabled by default or how to enable/disable this feature if you want to. I shouldn't have to read the source code to understand how to get the tool to do what I want it to.

**Comment by ben-eb** [comment]
It now should be clearer with v4's presets what option values are propagated:

https://github.com/ben-eb/cssnano/tree/master/packages/cssnano-preset-default#plugins
