### ISSUE TITLE
Can you compare cssnano and csso and another tools like this?

### ISSUE THREAD

**Issue by a-x-** [ben-eb/cssnano#370]

**Comment by a-x-** [comment]
I found some benchmark: https://goalsmashers.github.io/css-minification-benchmark/

**Comment by andyjansson** [comment]
The above benchmark is a bit outdated. We're on the verge of releasing a new version of cssnano which will have some much improved optimisations (with more to come in the future). You're welcome to test the alpha (`npm i cssnano@next`).
One thing to note is that we've introduced [presets](http://cssnano.co/guides/presets/); with the default preset only offering safe transformations. If you want more aggressive compression you might want to switch to the [advanced preset](http://cssnano.co/guides/optimisations/) (as well as maybe flip a few flags on the plugins). 

We'll look into putting a comparison up on the website after release.

**Comment by a-x-** [comment]
Thank you so much! ❤️
