### ISSUE TITLE
css modules @value breaks with cssnano

### ISSUE THREAD

**Issue by TheSisb** [ben-eb/cssnano#371]
Hey,

I am using webpack, cssloader with css modules turned on, and postcss (with cssnano).

```js
use: [
      'style-loader',
      {
        loader: 'css-loader',
        options: {
          modules: true,
          localIdentName: '[name]__[local]-[hash:base64:5]'
        }
      },
      {
        loader: 'postcss-loader',
        options: {
          parser: 'postcss-comment',
          plugins: [
            // ... some other stuff
            require('cssnano')({safe: true})
          ] 
        }
      }
    ]
```

In my css module file `test.mod.css`, I am doing
```css
@value vertical, center from './Flex.mod.css';
```

I'm getting the following error:
```
Module build failed: referenced class name "vertical" in composes not found (1:53)
```

The output css file looks like this, which is clearly incorrect
```
@value center from "./Flex.mod.css",vertical;  
```

I was wondering if anyone knew which optimization was causing this error?  

I'm using
```
"css-loader": "0.28.3",
"cssnano": "3.10.0",
"postcss-loader": "1.3.3",
```

**Comment by ben-eb** [comment]
Thanks for reporting, it's quite unfortunate that this is not transformed before it reaches cssnano as it's not a standard at-rule, but the fix is fairly trivial so I'm OK with supporting it. It'll be included with either the next release candidate or v4 itself.

**Comment by TheSisb** [comment]
Thanks!

**Comment by ben-eb** [comment]
The fix for this has been released in https://github.com/ben-eb/cssnano/releases/tag/v4.0.0-rc.1.
