### ISSUE TITLE
Cssnano removes @font-face

### ISSUE THREAD

**Issue by moimael** [ben-eb/cssnano#374]
Hi,
Cssnano is removing some of our @font-face definitions:

```
 @font-face {
  font-family: 'DIN Next LT Pro';
  font-style: normal;
  font-weight: normal;
  src: url('../../public/fonts/Linotype-DIN_Next_LT_Pro_Regular.woff2') format('woff2'),
    url('../../public/fonts/Linotype-DIN_Next_LT_Pro_Regular.woff') format('woff');
}

@font-face {
  font-family: 'DIN Next LT Pro';
  font-style: normal;
  font-weight: bold;
  src: url('../../public/fonts/Linotype-DIN_Next_LT_Pro_Bold.woff2') format('woff2'),
    url('../../public/fonts/Linotype-DIN_Next_LT_Pro_Bold.woff') format('woff');
}

@font-face {
  font-family: 'DIN Next LT Pro';
  font-style: normal;
  font-weight: 300;
  src: url('../../public/fonts/Linotype-DIN_Next_LT_Pro_Light.woff2') format('woff2'),
    url('../../public/fonts/Linotype-DIN_Next_LT_Pro_Light.woff') format('woff');
}

@font-face {
  font-family: 'DIN Next LT Pro Condensed';
  font-style: normal;
  font-weight: bold;
  font-stretch: condensed;
  src: url('../../public/fonts/Linotype-DIN_Next_LT_Pro_Bold_Condensed.woff2') format('woff2'),
    url('../../public/fonts/Linotype-DIN_Next_LT_Pro_Bold_Condensed.woff') format('woff');
}

@font-face {
  font-family: "universalavenue";
  src:url("../../public/fonts/universalavenue.eot");
  src:url("../../public/fonts/universalavenue.eot?#iefix") format("embedded-opentype"),
    url("../../public/fonts/universalavenue.woff") format("woff"),
    url("../../public/fonts/universalavenue.ttf") format("truetype"),
    url("../../public/fonts/universalavenue.svg#universalavenue") format("svg");
  font-weight: normal;
  font-style: normal;
}
```

By default the first 4 ones are discarded. I tried disabling a bunch of rules but cannot find which one is responsible for it. If i disable cssnano entirely, my @font-face rules work correctly.

**Comment by andyjansson** [comment]
Are the font families referenced somewhere? 3.x and below will filter out unused at-rules by default. If you want to disable this behaviour, you can set the `discardUnused` flag to `false`. Alternatively, you can try out our v4 alpha release which is safe by default (`npm i cssnano@next`) :wink:

**Comment by moimael** [comment]
Yes they are, it's our main website fonts. They are used all over the place. I tried to specifically disable the discardUnused rule already but it didn't change the behaviour. I tried to disable about half the rules which might vaguely be related to this without success. Only solution was to remove cssnano entirely.

**Comment by andyjansson** [comment]
Can you provide a minimal amount of CSS to reproduce the problem?

**Comment by andyjansson** [comment]
Closing this for now. I'll reopen if you can provide more information to reproduce the issue.

**Comment by rupl** [comment]
@andyjansson I was also experiencing this problem and I believe I've isolated it to the fact that oftentimes `@font-face` definitions are placed in their own file, leading the tool to mistakenly consider the rules to be unused.

I often place `@font-face` defs in their own file so I can load them asynchronously, use a font observer to monitor when they load, and progressively render a web page with fallbacks. My preferred file structure:

- `fonts.scss` containing `@font-face` rules
- `styles.scss` containing my site's implemented styles

I also noticed my `fonts.css` minified file was empty when using two files. However, when I made a test using a single file with the following contents:

```scss
@font-face {
  font-family: 'DIN-ar';
  font-weight: 400;
  font-style: normal;
  font-display: swap;
  src: url('../fonts/DIN Alternate Regular.otf') format('woff');
}

.el {
  font-family: 'DIN-ar';
}
```

cssnano did indeed minify as desired:

```css
@font-face{font-family:DIN-ar;font-weight:400;font-style:normal;font-display:swap;src:url("../fonts/DIN Alternate Regular.otf") format("woff")}.el{font-family:DIN-ar}
```

I realize it's a difficult ask to expect the minfier to infer intent and avoid discarding unused rules in this one situation. But in my case at least, it explains the difference between observed and expected behavior.

**Comment by rupl** [comment]
Using `cssnano@next` seems to restore the `@font-face` directives without having to insert a dummy rule within the file!  🎉 

I see that `postcss-discard-unused` is [disabled by default in 4.0.0 docs](http://cssnano.co/guides/optimisations/), which seems to do the trick. Thanks for the suggestion!

**Comment by evilebottnawi** [comment]
@rupl in near future we will finish all issue around `cssnano@next` and release new version

**Comment by rupl** [comment]
Thanks for your work to improve this already fantastic lib, I appreciate it!
