### ISSUE TITLE
Add preset webpack (`postcss-loader`)

### ISSUE THREAD

**Issue by michael-ciniawsky** [ben-eb/cssnano#376]
👋 

Reference https://github.com/postcss/postcss-loader/issues/262

`normalizeUrl` doesn't seem to be a safe transform, when using webpack :)

**Comment by ben-eb** [comment]
👋

Is it possible to locate what's causing the issue? `normalizeUrl` should be a safe transform, if it isn't it'd be good to remedy it. `webpack` preset sounds like a good idea. 👍

**Comment by clydin** [comment]
This appears to be an issue with the use of css-modules within css-loader (and webpack module resolution) in combination with the normalized URL.  For a web browser `./images/image.png` and `images/image.png` are equivalent.

**Comment by michael-ciniawsky** [comment]
I hadn't found the time yet to express the issue, yep normalized URL's `normalizeUrl` can be a problem for the abnormal `css-loader` :D 😛 if cssnano runs before (`postcss-loader`). I dunno if this needs to be adressed by `cssnano` directly, webpack edge cases tend to spread like cancer across other projects 😉 . Anyways @clydin thx for chiming in :)

**Comment by o-mega** [comment]
Is there any updates for current issue?

**Comment by andyjansson** [comment]
@o-mega The webpack guys are developing a new loader which should take care of the issue. I haven't heard anything from them in a while, though.

**Comment by o-mega** [comment]
@andyjansson Is there any way to disable only normalizeUrl and stay cssnano working normally with css-loader ?

**Comment by andyjansson** [comment]
@o-mega it's already disabled in css-loader by default: https://github.com/webpack-contrib/css-loader/blob/master/lib/processCss.js#L193-L199
