### ISSUE TITLE
Respect newLine at the end of the document

### ISSUE THREAD

**Issue by igloosi** [ben-eb/cssnano#378]
On the minified file, I'd like to keep a newLine.
Possible?

**Comment by andyjansson** [comment]
Out of curiosity, why would you want this? To the best of my knowledge, there's no built in way of accomplishing this, however, depending on your setup you should be able to append a newline when writing the output.

**Comment by ben-eb** [comment]
I don't think that there's much value in making this an option flag; I already feel that there's too many options here and it is confusing our user base, and it is one of the reasons I decided to implement the preset system to contain that complexity.

If you know that cssnano will always strip the ending newline, to add one back in is a matter of appending one to the result that comes back, something like this:

```js
const cssnano = require('cssnano');

cssnano.process('h1 { color: black }').then(result => {
    console.log(result.css + '\n');
});
```

Depending on how you consume cssnano you can write that css string to a file or do something else with it. I hope that helps. 😄
