### ISSUE TITLE
Node#moveTo was deprecated. Use Container#append.

### ISSUE THREAD

**Issue by dutchenkoOleg** [ben-eb/cssnano#379]
Get message when using cssnano as plugin in gulp-postcss
```shell
Node#moveTo was deprecated. Use Container#append.
```

**Comment by andyjansson** [comment]
What version of cssnano are you using?

**Comment by dutchenkoOleg** [comment]
3.10.0

**Comment by andyjansson** [comment]
Do you have a stacktrace?

**Comment by ben-eb** [comment]
It's because cssnano 3.x isn't officially compatible with PostCSS 6 - it *mostly* works but we use a couple of old methods, so that's why you see the warnings. Can you give version 4 a try and let me know how you get on?

```
npm install cssnano@next
```

**Comment by dutchenkoOleg** [comment]
Aha. That helped.
Tell me, is this a stable release? Can I use it in my work, or better wait for the official release cssnano@4.x?

**Comment by dutchenkoOleg** [comment]
@andyjansson Didn't quite understand what you mean

**Comment by ben-eb** [comment]
There were a lot of changes that were done without publishing for a while, so I wanted to make sure everything was OK before solidifying the API. I think it's mostly there though, but would appreciate some feedback. 😄

**Comment by dutchenkoOleg** [comment]
Ок. thx for helping

**Comment by guidobouman** [comment]
@ben-eb When switching from `3.10.x` (packaged with css-loader) to `4.0.0-rc.1` and loading it through postcss I went from a 20% decrease to an 10% increase of my CSS... Any idea how that might be happening? Removed cssnano from my package.json for now, and all seems fine apart from this one warning.

I'm on the latest postcss & postcss-loader, and run autoprefixer (together with other plugins) through it successfully.

PS: I do use the following config.

```js
{
  discardUnused: {
    fontFace: false // Required for fonts.css
  }
}
```

**Comment by guidobouman** [comment]
Wait, I'll open a new issue.

**Comment by jimblue** [comment]
Getting exactly the same error message on my webpack config using `postcss`.
Will wait for stable version 4 as the current version is actually more effective.
Any idea of the release date?
Thanks anyway for this nice piece of shrinking code.

**Comment by ben-eb** [comment]
@jimblue With the default preset yes, it is less effective but this is by design. From the [release notes](https://github.com/ben-eb/cssnano/releases/tag/v4.0.0-rc.0):

> * By default, the following transforms are no longer applied to any input CSS.
>   You may see an increased output file size as a result:
>
>   * `autoprefixer`
>   * `postcss-discard-unused`
>   * `postcss-merge-idents`
>   * `postcss-reduce-idents`
>   * `postcss-zindex`
>
> Note that you can load `cssnano-preset-advanced` instead which _does_ contain
these transforms.

Not sure on final release date, I think this will require another release candidate. Mostly it's there though.

**Comment by mischah** [comment]
Hej @ben-eb, 

I just saw that there where 6 commits to master since this v4.0.0-rc.2. 
Do have plans when to release 4.0.0 final?

Cheers, Michael

**Comment by rcalabro** [comment]
+1
cssnano@next is breaking the build

**Comment by rcalabro** [comment]
Something to do with 'advanced' presets:
`ModuleBuildError: Module build failed: ModuleBuildError: Module build failed: Error: Cannot load preset "advanced". Please check your configuration for errors and try again.`

What is the equiv for v4.0.0-rc.2.

**Comment by TheY2T** [comment]
I updated to v4.0.0-rc.2 but I'm still getting the same error unfortunately...

**Comment by ashkaushik** [comment]
Please update "@angular/cli" to "1.7.3"

Step 1: npm remove @angular/cli
Step 2: npm cache clean --force
Step 3: npm install -g @angular/cli@1.7.3

Still stuck then update your package.json with

"@angular/cli": "1.7.3" and run npm install

Tested and working for me

**Comment by zymr-keshav** [comment]
typo  in Step3:

npm install -g ~$~ @angular/cli@1.7.3

**Comment by seanret** [comment]
test

**Comment by seanret** [comment]
npm -burat

**Comment by seanret** [comment]
npm -burat
