### ISSUE TITLE
".from" class name is transformed

### ISSUE THREAD

**Issue by michael-ygt** [ben-eb/cssnano#38]
I work with "from prices" and use a class named `.from`. The transform that checks @keyframes isn't sufficiently specific, so:
```
.from {
  display: block;
}
```
becomes
```
0%{display:block}
```

**Comment by TrySound** [comment]
@michael-ygt Try it on https://github.com/ben-eb/postcss-minify-selectors, please. Need to locate problem.

**Comment by ben-eb** [comment]
Looked at the logic and yeah it looks like it isn't specific enough. Thanks for reporting. :+1:

**Comment by ben-eb** [comment]
Published a fix in postcss-minify-selectors @ `1.4.3`.
