### ISSUE TITLE
Question about cssnano mergeLonghand, how to use it with webpack?

### ISSUE THREAD

**Issue by TimRChen** [ben-eb/cssnano#383]
I want ask a question about cssnano mergeLonghand, how to use it with webpack? the documention: http://cssnano.co/optimisations/mergelonghand/

I don't know why this is no any api? How can use it in vue-cli?

Thank you for solve this question.

**Comment by andyjansson** [comment]
`mergeLonghand` is part of cssnano, which in turn is bundled with webpack's [css-loader](https://github.com/webpack-contrib/css-loader). You can also load cssnano explicitly via [postcss-loader](https://github.com/postcss/postcss-loader). If you're just interested in [mergeLonghand](https://github.com/ben-eb/postcss-merge-longhand), you can load it as a standalone postcss plugin via the latter loader. 

Hope this answers your question.

**Comment by TimRChen** [comment]
I dont know how to show you my gratitude, but I really appriciate of what you have done to me.

**Comment by andyjansson** [comment]
That's quite a response :smile:
