### ISSUE TITLE
Floating point numbers in calc() are scrambled when percentages are summed up

### ISSUE THREAD

**Issue by AngularPadawan** [ben-eb/cssnano#394]
When the following css is minified using cssnano:
```

h1 {
    width: calc(14.84375% + 0.78125% + 1.5625%);
}
```

the resulting css contains scrambled floating point numbers:
`h1{width:calc(0.1484375 + .781.25 + 0.015625)}`

A workaround is to add "+ 0px" to the calc argument:
```
h1 {
    width: calc(14.84375% + 0.78125% + 1.5625% + 0px);
}

```
correctly becomes

`h1{width:calc(14.84375% + .78125% + 1.5625% + 0px)}`

Versions:
"cssnano": "3.10.0",
    "postcss-cli": "4.1.0"

**Comment by andyjansson** [comment]
I can confirm that this is a bug in cssnano 3.x. The behaviour seems to have been fixed in the v4 alphas. You can try the alpha out by running `npm i cssnano@next`.

**Comment by AngularPadawan** [comment]
Thanks for the reply! We use cssnano through angular-cli, so I guess we will have to wait until it is pushed to version 4 there. With the workaround mentioned above not a problem at all.

**Comment by gustavohenke** [comment]
Thanks for the hint regarding the `+ 0px` hack, @AngularPadawan - that really helps while css-loader doesn't update to cssnano v4.
