### ISSUE TITLE
Comparison of minification results and performance

### ISSUE THREAD

**Issue by shinnn** [ben-eb/cssnano#4]
I would like to see the comparison with other CSS optimization tools (e.g. [clean-css](https://github.com/jakubpawlowicz/clean-css)) in the README, like [kangax/html-minifier](https://github.com/kangax/html-minifier) repo.

| name | original size (KB) | optimized size (KB) | optimization time (ops/sec) |
| --- | --- | --- | --- |
| cssnano | ... | ... | ... |
| clean-css | ... | ... | ... |
| csscomb | ... | ... | ... |
| other tools | ... | ... | ... |

**Comment by shinnn** [comment]
Ah, I found [a good project](https://github.com/GoalSmashers/css-minification-benchmark) that meets my requirements and [I added cssnano to the list of CSS minifiers](https://github.com/GoalSmashers/css-minification-benchmark/pull/37).

Now we can make a comparison with other CSS minifiers here: https://goalsmashers.github.io/css-minification-benchmark/

**Comment by ben-eb** [comment]
You may also be interested in https://github.com/ben-eb/css-minifier-tests :smile:

**Comment by ben-eb** [comment]
You may also be interested in https://github.com/ben-eb/css-minifier-tests :smile:
