### ISSUE TITLE
There should be a way to disable “safe” optimizations too

### ISSUE THREAD

**Issue by kizu** [ben-eb/cssnano#40]
While some of optimizations could be safe indeed, there always could be errors and bugs that would make them unsafe. In those cases there should be a way to disable those safe optimizations to prevent the code from breaking while still using cssnano.

**Comment by TrySound** [comment]
@kizu Just disable cssnano. We will fix every problem as soon as it possible.

**Comment by kizu** [comment]
@TrySound That's not helpful. Users of cssnano shouldn't depend on the release and development cycle of cssnano, when they'd need it to work right here and right now. When there are two options: to disable the broken plugin or disabling cssnano at all, if only the later is possible, it is easier to choose a different minifier at all.

**Comment by ben-eb** [comment]
My main concern with this was the increased documentation under the current format, where each plugin has a namespace for options. It seems like a better way is just to allow users to specify the full module name (https://github.com/ben-eb/cssnano/pull/35), which I am considering making the primary behaviour.

This means that the documentation will not be as large, which should help new users, and also make the module more customisable. The downside is that the option object will have more complex keys, but I think its an acceptable tradeoff.

**Comment by ben-eb** [comment]
Available since `2.5.0`. Please consult the new documentation. :smile:

http://cssnano.co/options/
