### ISSUE TITLE
Docs/site cover 4.0, NPM brings down 3.10.0

### ISSUE THREAD

**Issue by benfrain** [ben-eb/cssnano#404]
Just got the latest version down from npm (3.10.0) and stuggled for 10 minutes or so to understand why the 

```
preset: 'default',
```

Type stuff wasn't working. Take it this is due to the docs reflecting version 4.0 and not 3.x?

Might be worth including some info on installing the v4 version via NPM as it seems like nano just isn't working.

**Comment by andyjansson** [comment]
4.0 is still in pre-release, so that's why you don't get it when you install by npm. 

If you want to try it out, go ahead and install it by running `npm i cssnano@next`

**Comment by benfrain** [comment]
Yes, I get that now. My point is that coming to the site 'fresh' and following the instructions it doesn't work as documented ;)

Perhaps just add "Current documentation reflects the forthcoming v4.0 release. To get the pre-release version of cssnano run `npm i cssnano@next`" to the site content?

**Comment by andyjansson** [comment]
>Perhaps just add "Current documentation reflects the forthcoming v4.0 release. To get the pre-release version of cssnano run npm i cssnano@next" to the site content?

Like the one on the homepage? :smile: 

In all seriousness though, I do think it could stand out a bit more. Perhaps even be added to all the pages in the guide. 

>And maybe link to the old docs for users that want info regarding the version NPM will serve them by default.

Yup, I agree.
