### ISSUE TITLE
cssnano enables optimizations that should have been disabled by the default preset

### ISSUE THREAD

**Issue by tyrak** [ben-eb/cssnano#407]
I started experimenting with cssnano and I seem to have trouble understanding how to use the presets. I am trying to use the default preset, but it appears that all optimizations are enabled, even those that shouldn't have been according to the [optimizations page](http://cssnano.co/guides/optimisations/).

For example, suppose that we have the following input file:

    @keyframes fadeOut {
        from {
            opacity: 1;
        }
        to {
            opacity: 0;
        }
    }

and the following `postcss.config.js`:

    module.exports = {
        plugins: [
            require('cssnano')({
                preset: 'default',
            }),
        ],
    };

Then running `postcss test.css > out.css` produces an empty output file, i.e. it eliminates the `keyframes` declaration, as if the `discardUnused` optimization was enabled. If I add `discardUnused: false` then the `keyframes` declaration is preserved.

What am I doing wrong?

**Comment by andyjansson** [comment]
The documentation is for the upcoming 4.0 version (which you're welcome to try by using `npm i cssnano@next`). One important change between 4.0 and 3.x is that configurations now happen via presets, and that the default preset is safe by default.

**Comment by tyrak** [comment]
Ok thanks. It is a bit confusing.

**Comment by andyjansson** [comment]
I know, sorry about that. We'll try to make the documentation more explicit.
