### ISSUE TITLE
Documentation problem for convertValues

### ISSUE THREAD

**Issue by EECOLOR** [ben-eb/cssnano#409]
At http://cssnano.co/optimisations/convertvalues/ it states:
> Converts between equivalent length, time & angle values. Note that by default, length values are not converted.

In the readme it states:
> *length*
>
> Type: `boolean` Default: `true`

The source code seems to agree with the readme. This is a difference with the 'isSafe' option in version 3, so the default should probably be false

**Comment by andyjansson** [comment]
Looks to me like it's disabled in the default preset: 

https://github.com/ben-eb/cssnano/blob/master/packages/cssnano-preset-default/src/index.js#L47

**Comment by EECOLOR** [comment]
Ahh, then the documentation at http://cssnano.co/guides/optimisations/ is not correct, it shows it as enabled.

**Comment by EECOLOR** [comment]
Oh, and my first report still holds true as well, the documentation does not comply with the readme of the optimazation.

**Comment by andyjansson** [comment]
The plugin is enabled, but the `length` option is disabled in both presets. Seems correct to me.

**Comment by EECOLOR** [comment]
I'm sorry man, I must have been looking with my nose.
