### ISSUE TITLE
Invalid css generated through colormin

### ISSUE THREAD

**Issue by zakalwe314** [ben-eb/cssnano#413]
First of all thank you for your excellent work, we use cssnano a lot.

We had the a failure of styling of a component imported from vue-mdl after css minification.  We tracked it down to where there is an rgb color and image url both specified.

To reproduce, using the cssnano-cli:
`echo .foo{background:rgb(1,2,3)url(bar.png) | cssnano` which gives the output as `.foo{background:#010203url(bar.png)}`.  

Leaving no space between `rgb()` and `url()` is valid syntax, unfortunately between `#...` and `url()` it is not.

**Comment by andyjansson** [comment]
What version are you using?

**Comment by zakalwe314** [comment]
3.10.0 - the latest AFAIK
