### ISSUE TITLE
Unknown protocols are transformed incorrectly

### ISSUE THREAD

**Issue by mrkishi** [ben-eb/cssnano#414]
It seems `cssnano` breaks urls with unknown protocols.

`url('moz-extension://some/path')` gets turned into `url('http://moz-extension/some/path')`, while `url('chrome-extension://some/path')` is treated correctly.

**Comment by fvoordeckers** [comment]
Same issue here, `http://` is added in front of every link starting with `moz-extension://`.
Fix ready?

**Comment by fvoordeckers** [comment]
Fixed it in the `postcss-normalize-url` package.
Pull request: https://github.com/ben-eb/postcss-normalize-url/pull/26

**Comment by andyjansson** [comment]
@fvoordeckers this is the new location for postcss-normalize-url https://github.com/ben-eb/cssnano/tree/master/packages/postcss-normalize-url

**Comment by fvoordeckers** [comment]
@andyjansson created the PR for this repo. 

https://github.com/ben-eb/postcss-normalize-url will not be maintained any longer?
