### ISSUE TITLE
How to use nanocss plugins?

### ISSUE THREAD

**Issue by BamiGorengo** [ben-eb/cssnano#417]
Sorry that i use this issue board to ask questions. but i cant find any documentations about using nanocss plugins.

I try just installed some plugins and add them to my .postcssrc.json like this:

```
{
  "plugins": {
    "autoprefixer": {
    },
    "cssnano": {
      "safe": true,
      "discardComments": {
        "removeAll": true
      },
      "colormin": {

      },
      "discardUnused": {

      },
      "discardDuplicates": {

      },
      "reduceTransforms": {

      },
      "minifyGradients": {

      },
      "zindex": {

      }
    }
  }
}
```

In most of the cases i dont setup any config, because i want to use the defaults. On some plugin repositorys arent any options listed. (There is any external documentation about the plugins?)

But actually only discrdComment do something, all other plugins dont do anything. And im an wondering about discardComments, because he remove all comments, but not the sourcemaps in the css files. they are commented out to... so why they dont get removed?

Best regards.

**Comment by andyjansson** [comment]
The documentation on the cssnano website is for the upcoming v4 release. Any options in v3 need to be passed to the cssnano instance.
