### ISSUE TITLE
Where is old documentation for version 3.xx?

### ISSUE THREAD

**Issue by Tiendq** [ben-eb/cssnano#425]
Why is there no link to documentation for current version 3.xx? I know `next` version is awesome but as long as it's not officially released, please keep everything for current version's users.

Thanks,

**Comment by chriseppstein** [comment]
Sorry, it's inconvenient, but reinstating the old version isn't possible at this time due to having lost Ben as a maintainer. We'll get 4.0 out as soon as possible. Subscribe to #408 for updates.
