### ISSUE TITLE
Weird Bug: cssnano conflict with file-loader

### ISSUE THREAD

**Issue by amerllica** [ben-eb/cssnano#427]
My project link is [THIS LINK](https://github.com/amerllica/postcss-config-on-webpack).
when I use `npm run build:dev` everything is ok but when use `npm run build:dist` , file-loader doesn't work, it seems that doesn't exist. Actually with second command I use `webpack.prod.js` config file for webpack build, and `cssnano` is loaded in LINE:65, and existence of `cssnano` cause to file-loader doesn't work.

When I comment from LINE:65 to LINE:70 and then run again `npm run build:dev` everything run properly.

**# existence of `cssnano` cause to file-loader doesn't work**

**Comment by michael-ciniawsky** [comment]
What do you exactly mean by doesn't work? Do you get any errors in the browser console that e.g asset x could not be loaded and if so could you post them here please? Disabling the `normalizeUrl` option in `cssnano` is a good start

**Comment by amerllica** [comment]
Dude, I'm not junior, when I said `doesn't work` it means file-loader  `doesn't work` . it seems the file-loader packages doesn't exist. I loaded font files with file-loader but when `cssnano`  added to my webpack postcss config the file-loader doesn't work. @ai told me I use `csso` but I believe `cssnano`  is better.

**Comment by andyjansson** [comment]
>Dude, I'm not junior, when I said doesn't work it means file-loader doesn't work .

I suggest you adjust your attitude. Don't get snippy with people trying to help you.

**Comment by amerllica** [comment]
@andyjansson , Absolutely you are right, I regretted my words and attitude and learned to won't it no longer. thanks both of you and @michael-ciniawsky
