### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by debradley** [ben-eb/cssnano#43]
Version 2.2 of cssnano fails on files that 2.1 processes without error. The output from 2.2 is: TypeError: Cannot read property 'split' of undefined.

How can I get more detailed information about the failure in order to provide you with a more useful bug report?

**Comment by ben-eb** [comment]
Full stack trace would be useful. Is this related perchance? https://github.com/cssnext/cssnext/issues/193

**Comment by debradley** [comment]
I am not using cssnext (unless some dependency is using it indirectly). cssnano is the last step in my postcss process. If I remove it from the chain, postcss succeeds. If I then run its output through cssnano I get the following stack trace:

/myproject/node_modules/postcss/lib/lazy-result.js:200
            throw error;
                  ^
TypeError: Cannot read property 'split' of undefined
    at /myproject/node_modules/cssnano/node_modules/postcss-merge-rules/index.js:93:41
    at /myproject/node_modules/postcss/lib/container.js:102:26
    at Rule.each (/myproject/node_modules/postcss/lib/container.js:89:22)
    at Rule.eachInside (/myproject/node_modules/postcss/lib/container.js:101:21)
    at partialMerge (/myproject/node_modules/cssnano/node_modules/postcss-merge-rules/index.js:105:17)
    at /myproject/node_modules/cssnano/node_modules/postcss-merge-rules/index.js:155:17
    at /myproject/node_modules/postcss/lib/container.js:141:30
    at /myproject/node_modules/postcss/lib/container.js:102:26
    at Root.each (/myproject/node_modules/postcss/lib/container.js:89:22)
    at Root.eachInside (/myproject/node_modules/postcss/lib/container.js:101:21)

(I've replaced the actual path name with 'myproject')

**Comment by ben-eb** [comment]
This should be fixed since https://github.com/ben-eb/postcss-merge-rules/commit/a80a34547d2cd45fa9105a22e42771dd20dc689f (postcss-merge-rules@1.3.2). Thanks for reporting. :+1:

**Comment by debradley** [comment]
Thanks for jumping on it. Do you still need to bump the postcss-merge-rules dependency in cssnano?

**Comment by ben-eb** [comment]
Nope, npm will automatically download the patch because of semantic versioning. :smile:
