### ISSUE TITLE
Removing quotes of font-family will make it invalid

### ISSUE THREAD

**Issue by ysyfff** [ben-eb/cssnano#434]
Remove the quotes will cause "invalid property value" error in chrome (of version 63.0.3239.132, may be in any version)
![image](https://user-images.githubusercontent.com/2571290/35669913-ac4d0e90-0771-11e8-8da9-09662114ba5f.png)

**Comment by tamagokun** [comment]
YES THIS. spent hours figuring out where this was happening down the build chain.

I can confirm this in both Chrome and Firefox

**Comment by veltman** [comment]
I'm seeing this too - specifically, the error seems to occur if a quoted font name includes a generic font family keyword in its name (e.g. `monospace` or `cursive), so `Monospace Number` can't be unquoted:

VALID:
`font-family: "Some Custom Font";`
`font-family: Some Custom Font;` (no quotes)
`font-family: "Monospace Custom Font";`
`font-family: "Cursive Custom Font";`

INVALID:
`font-family: Monospace Custom Font;`
`font-family: Cursive Custom Font;`

Absent the ability to selectively quote fonts based on a list of keywords, leaving the quotes seems like the safer default.
