### ISSUE TITLE
cssnano fubars animations

### ISSUE THREAD

**Issue by phun-ky** [ben-eb/cssnano#436]
I am using `cssnano` through `postcss-loader` and with `webpack`-plugins through `optimize-css-assets-webpack-plugin` in my production builds, which results in ~almost all my animations (`@keyframes`/`transforms`) not working as intended.~ the animations for `react-joyride` not working as intended. The placements of the tooltips are way off. I checked the animations between the production build and the development build, and they are mangled in a way that fubars the placement and animation.

> The retraction here is that I forgot to install the latest version of cssnano, all other animations now work, but not the animations/transforms from `react-joyride` is still not working as intended, most likely due to the mangling provided from `cssnano`

An example:

In development build (the computed value found in inspector):

    transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -1, 0, 0, 0, 1);

In production build (the computed value found in inspector): 

    transform: matrix(1, 0, 0, 1, 450, -103.125);

According to the MDN documentation here: https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/matrix, the `matrix(a, b, c, d, tx, ty)` is a shorthand for `matrix3d(a, b, 0, 0, c, d, 0, 0, 0, 0, 1, 0, tx, ty, 0, 1)`. So, the translated matrix does not fit the shorthand, as described under:

    (a, b, 0, 0, c, d, 0, 0, 0, 0, 1, 0, tx, ty, 0, 1)
    // Look at the 12th value, it does not fit into the shorthand
    // And where would the values  450, -103.125 come from?
    (1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -1, 0, 0, 0, 1)
    (a, b, c, d, tx, ty)
    (1, 0, 0, 1, 0, 0)    

I think that transform comes from this relevant animation (before css processing):

    @keyframes joyride-tooltip {
      0% {
        -webkit-transform: scale(0.1);
                transform: scale(0.1); }
      100% {
        opacity: 1;
        -webkit-transform: perspective(1px) scale(1);
                transform: perspective(1px) scale(1); } }

Used in this relevant css (before css processing):

    .joyride-tooltip {
      background-color: #fff;
      border-radius: 4px;
      color: #555;
      cursor: default;
      -webkit-filter: drop-shadow(-1px -2px 3px rgba(0, 0, 0, 0.3)) drop-shadow(1px 2px 3px rgba(0, 0, 0, 0.3));
              filter: drop-shadow(-1px -2px 3px rgba(0, 0, 0, 0.3)) drop-shadow(1px 2px 3px rgba(0, 0, 0, 0.3));
      opacity: 0;
      padding: 20px;
      pointer-events: auto;
      -webkit-transform: translate3d(0, 0, 0);
              transform: translate3d(0, 0, 0);
      width: 290px;
      z-index: 1510; }
      .joyride-tooltip--animate {
        -webkit-animation: joyride-tooltip 0.4s forwards;
                animation: joyride-tooltip 0.4s forwards;
        -webkit-animation-timing-function: cubic-bezier(0, 1.05, 0.55, 1.18);
                animation-timing-function: cubic-bezier(0, 1.05, 0.55, 1.18); }

These are my relevant configs:

### webpack.config.js

    module: {
      rules: [
          {
          test: test_expressions.css,
          loader: extractTextPlugin.extract({
            fallback: 'style-loader',
            use: [
              {
                loader: 'css-loader',
                options: {
                  importLoaders: 1
                }
              },
              {
                loader: 'postcss-loader'
              }
            ]
          })
        },
        {
          test: test_expressions.stylus,
          loader: extractTextPlugin.extract({
            fallback: 'style-loader',
            use: [
              {
                loader: 'css-loader',
                options: {
                  importLoaders: 2
                }
              },
              {
                loader: 'postcss-loader'
              },
              {
                loader: 'stylus-loader'
              }
            ]
          })
        },
        {
          test: test_expressions.sass,
          loader: extractTextPlugin.extract({
            fallback: 'style-loader',
            use: [
              {
                loader: 'css-loader',
                options: {
                  importLoaders: 2
                }
              },
              {
                loader: 'postcss-loader'
              },
              {
                loader: 'sass-loader'
              }
            ]
          })
        },
      ]
    },
    plugins: [
      new OptimizeCssAssetsPlugin({
        assetNameRegExp: /\.css$/
      })
    ]

### .postcssrc.js

    module.exports = {
      plugins: [
        require('cssnano')({
          preset: [
            'advanced',
            {
              reduceIdents: {
                exclude: true
              },
              mergeIdents: {
                exclude: true
              },
              discardUnused: false,
              reduceTransforms: {
                exclude: true
              },
              discardDuplicates: true,
              discardOverridden: {
                exclude: true
              },
              autoprefixer: { add: true },
              zindex: {
                exclude: true
              }
            }
          ]
        })
      ]
    };

### Relevant deps

    "optimize-css-assets-webpack-plugin": "^3.1.1",
    "postcss-loader": "^2.1.0",
    "poststylus": "^0.2.2",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.18.2",
    "css-loader": "^0.28.4",
    "cssnano": "4.0.0-rc.2",
    "cssnano-preset-advanced": "^4.0.0-rc.2",
    "node-sass": "^4.7.2",
    "webpack": "^3.5.5",
    "react-joyride": "^1.11.1",
    "extract-text-webpack-plugin": "^3.0.0",

### Backstory
This is the status after trying to figure out another initial issue with animations, after including `react-joyride` and it's compiled css (or uncompiled scss) in my  production build, the component was not acting as intended. I checked the animations in the compiled css and found that they differed from the development build (as in wrong placement due to mangled transforms). I then tried to upgrade and test new `cssnano` and `postcss-loader` versions, but nothing changed.

Here are my previous configs:

#### .postcssrc.js

    module.exports = {
      plugins: [
        require('cssnano')({
          reduceIdents: false,
          reduceTransforms: false,
          discardDuplicates: true,
          autoprefixer: { add: true },
          zindex: false
        })
      ]
    };

#### Relevant old deps

    "cssnano": "^3.10.0",
    "react-joyride": "^1.11.1",
    "postcss-loader": "^2.0.6",

**Comment by phun-ky** [comment]
To give some more information, both for me and this issue, here is the configs I am currently trying to get this to work:

|Config|Result|
|------|------|
|https://gist.github.com/phun-ky/e8e7b8d41b57ce5347fce3821b0a1958|The animations from `react-joyride` works, but some scaling transforms and z-index are broken|
|https://gist.github.com/phun-ky/727f42ff301c359cf74a0269e8a32942|The animations from `react-joyride` does not work correctly, but the rest of the transforms seem to work| 
|https://gist.github.com/phun-ky/a42b8c78124520c4caf10123169771b7|Same as above|
|https://gist.github.com/phun-ky/10f0f4a81697275e647f6e86c2f78dbe|Same as above|
|https://gist.github.com/phun-ky/649d7dc4589186a973be8cdc01e2f033|Same as above|

I am currently firing blanks here to what can fix this.

**Comment by phun-ky** [comment]
Ok. The issue is resolved, for my part, but as mentioned in the comment above, there are some unanswered questions that might be clarified, either in the docs for `cssnano` or `postcss` or `postcss-loader`

**Comment by NMFR** [comment]
On `optimize-css-assets-webpack-plugin`s part, it simply delegate the CSS manipulation to `cssnano` (by default) or a custom `cssProcessor`. 
The only way i see this being a problem in `optimize-css-assets-webpack-plugin` is if there is an issue with the `cssnano` version we depend on (currently ´^3.4.0´) and this goes away when you require your version into the `cssProcessor` config.
That can be checked by removing the config line `cssProcessor: require('cssnano'),` and checking if the issue occurs.

**Comment by phun-ky** [comment]
@NMFR Okay, maybe there's another issue here, and that is that `postcss-loader` uses a `.postcssrc.js` as a config file, and that `optimize-css-assets-webpack-plugin` does not? Hm, no that does not add up, since before the animations broke, I had this `.postcssrc.js` specifically to be used with `optimize-css-assets-webpack-plugin`:

    module.exports = {
      plugins: [
        require('cssnano')({
          reduceIdents: false,
          reduceTransforms: false,
          discardDuplicates: true,
          autoprefixer: { add: true },
          zindex: false
        })
      ]
    };

And only had this in my `plugins`-sections of my `webpack.config.js`:

    new OptimizeCssAssetsPlugin({
      assetNameRegExp: /\.css$/
    })
