### ISSUE TITLE
Link broken for "options" and "usage" on NPM.

### ISSUE THREAD

**Issue by obedparla** [ben-eb/cssnano#438]
On npm, the links are broken for "Installation guide for your build process" and "Customise the output (options documentation)" They both direct to a 404 on the cssnano site.

Wasn't sure if this sort of issue should be reported here, advice me if I'm wrong! 

Thanks.

**Comment by andyjansson** [comment]
npm has the v3 release, while the cssnano website documents v4 (release candidate). It's unfortunate that we didn't keep the v3 documentation intact, and it's something we should rectify in the future.
