### ISSUE TITLE
declaration sorter missing in official documentation

### ISSUE THREAD

**Issue by studio404pl** [ben-eb/cssnano#440]
it would be good to list this module in documentation. It was breaking svg fallback rules by reordering background position rule. Found mention only in changelog.

`cssDeclarationSorter: false`

helped.

**Comment by evilebottnawi** [comment]
Done http://cssnano.co/guides/optimisations/ and http://cssnano.co/guides/optimisations/
Also can you create new issue around bugs in `cssDeclarationSorter`?
