### ISSUE TITLE
Who is using cssnano?

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/cssnano#45]
I'd like to add an area to the [cssnano website](http://cssnano.co/) with some company logos and links back to websites that use cssnano, with a minimum of 6 companies. If there are a lot of submissions then I will consider doing a separate page, but if there are only a few then I will dedicate a small section on the homepage for this.

If you'd like to get your company on this list, then I'd like an SVG of your logo & any brand guidelines for its use, your company name (correctly formatted) and of course your company homepage.

Thanks. :heart:

**Comment by TrySound** [comment]
[![Author24](http://author24.ru/assets/images/v1/big_logo.png)](http://author24.ru)

**Comment by demiazz** [comment]
https://ebaysocial.ru

**Comment by ai** [comment]
<img src="https://cloud.githubusercontent.com/assets/19343/10538493/9fd0662e-73f0-11e5-868a-d1257e2f94c6.png" width="100" height="100">

[Amplifr](https://amplifr.com)

**Comment by neonick** [comment]
![Digital Sector](http://neonick.ru/ds/img/logo.svg)
[Digital Sector](http://digital-sector.ru/) (new site will be very [soon](http://neonick.ru/ds))

**Comment by ai** [comment]
<img src="https://camo.githubusercontent.com/ebc085019011ababb0d35024824304831c7dc72a/68747470733a2f2f7765627061636b2e6769746875622e696f2f6173736574732f6c6f676f2e706e67" height="150px">

Also webpack and every webpack users [uses](https://github.com/webpack/css-loader/blob/master/package.json#L8) cssnano.

**Comment by ben-eb** [comment]
@ai Yeah, and cssnext too. :smile:

**Comment by simonsmith** [comment]
Using it at the BBC on an unreleased project. Not sure about logo rules so I'll let you track one down from a press page or something :)

**Comment by tjconcept** [comment]
![icon-only](https://cloud.githubusercontent.com/assets/801895/10554839/70b0b4e4-7467-11e5-990a-20be02be8120.png)
[Paylike](https://paylike.io)
SVG logos: https://github.com/paylike/press/tree/master/logo

**Comment by outpunk** [comment]
<img src='https://evilmartians.com/evilmartians.svg' width='200' />
[Evil Martians](https://evilmartians.com)

**Comment by rafaelrinaldi** [comment]
<img src=https://cloud.githubusercontent.com/assets/87162/14962497/1c8a87bc-106d-11e6-9633-a4538b7b82d8.jpg width=150 />
http://work.co

---
<sup>Click on the image for the full size version</sup>

**Comment by oskarkrawczyk** [comment]
<img width="256" alt="screen shot 2016-05-02 at 19 51 48" src="https://cloud.githubusercontent.com/assets/34213/14962504/7412677a-109f-11e6-9ec7-b86b930ca2fb.png">

JSFiddle 

([svg](https://www.dropbox.com/s/09txl1bpe97g2ca/jsfiddle-logo-name.svg?dl=1))

**Comment by efedorenko** [comment]
[Beanstalk](http://beanstalkapp.com)

![Beanstalk logo](https://s3.amazonaws.com/wildbit-assets/beanstalk-logo.svg)

**Comment by marcobiedermann** [comment]
Maybe this will show some project:
https://www.google.de/#q=site:https://github.com+inurl:package.json+cssnano

**Comment by ben-eb** [comment]
Now that I have the [new site](http://cssnano.co/), I'd appreciate it if these were sent in as pull requests directly. Going to close this issue, thanks for all your submissions. 👍
