### ISSUE TITLE
Why is the z-index reverting to 1 issue not fixed yet?

### ISSUE THREAD

**Issue by emd2013** [ben-eb/cssnano#459]
Reference: https://github.com/ben-eb/gulp-cssnano/issues/8

**Comment by sishbi** [comment]
I just got caught by this too - according to the cssnano.co page the zindex plugin should be disabled by default but it seems that it is!
Please fix this... Luckily the work-around is simple.

**Comment by evilebottnawi** [comment]
@andyjansson we can close this issue, because in `4` version it is unsafe and disable by default

**Comment by jimi75** [comment]
Using `4.1.10` and z-index change. Additional disabled `zindex`  do not work.

`require('cssnano')({
      preset: ['default', { zindex: false }],
    }),`
