### ISSUE TITLE
Roadmap for version 3.

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/cssnano#46]
Wanted to get some feedback on the next version of cssnano, and see if this plan is line with everyone's expectations.

After a *lot* of feedback from users (https://github.com/ben-eb/cssnano/issues/24, https://github.com/ben-eb/cssnano/issues/27, https://github.com/ben-eb/cssnano/issues/28, https://github.com/ben-eb/cssnano/issues/40) & a proposed pull request https://github.com/ben-eb/cssnano/pull/35, I've decided to give users the ability to disable any part of cssnano that they choose. But I want to do it in a way that is easily documentable and easy to configure. What I am proposing is that each optimisation can *either* be camelCased, like `postcssMergeRules` *or* specified as the module name like `postcss-merge-rules`. Furthermore, I would like the `postcss` prefix to be optional, so that a configuration looks more like this:

```js
{
  autoprefixerCore: {browsers: 'last 3 versions'},
  discardComments: {removeAll: true},
  mergeIdents: false,
  mergeRules: false
}
```

The idea for this will be implemented in `2.x`, and current options will print deprecation warnings until `3.x`. `3.x` will also remove the synchronous API in favour of an asynchronous, promise based one. This is so that we can bundle https://github.com/ben-eb/postcss-svgo as a further optimisation. At the same time I will look into bundling https://github.com/ben-eb/stylehacks, which will likely share a `browsers` option with autoprefixer.

Another idea that I am considering is to implement a `safe` option, which will disable all unsafe optimisations like postcss-zindex etc, which rely on a whole site's CSS to be passed in to be safe.

Other than that, the next optimisations are looking at longhand merging https://github.com/ben-eb/cssnano/issues/44 & anything left over in https://github.com/ben-eb/cssnano/issues/7.

**Comment by davidtheclark** [comment]
I think these are all necessary changes. Good work.

**Comment by ben-eb** [comment]
On second thought I'm not going to deprecate the `autoprefixer` option for `autoprefixerCore`, as when people think of the module they probably won't think of the 'core' module that is used here. The other changes stand though.

**Comment by ben-eb** [comment]
The new options are available, see http://cssnano.co/options/ - additionally https://github.com/ben-eb/cssnano/issues/44 was resolved this week.

Furthermore, now that PostCSS 5.0 is out, I would like to convert all modules to use it when 3.0 is out.

**Comment by ben-eb** [comment]
Current progress is on https://github.com/ben-eb/cssnano/tree/3.0. Waiting for @ai to patch autoprefixer so that we can migrate to PostCSS 5.x. :smile:

**Comment by TrySound** [comment]
Added new module
https://github.com/TrySound/postcss-minify-params

**Comment by ben-eb** [comment]
More optimizations will be done in minor releases. Didn't have the time to look at stylehacks for 3.0.

**Comment by TrySound** [comment]
- [ ] Screenshot testing
- [ ] Looking into more-css

**Comment by ai** [comment]
@ben-eb “Screenshot testing” is #55

**Comment by ben-eb** [comment]
At this stage I think I'd like to move all features that have been considered for v3 to the v4 roadmap, and close this issue to reduce my cognitive load of this project. :smile:

Just a few points on any loose ends here:

* CSS hack removal should be considered an advanced optimisation, probably not bundled by default.
* Longhand merging needs a big refactor which Andy and I were working on, progress has stalled for the time being; there were still some outstanding bugs, although the early work has been really promising. Hopefully v4 will provide better merging support.
* Happy for anyone to offer insight into more-css, I don't have the time to investigate this right now.
* Screenshot testing is a *really big project* which I will not get time to do. I am happy to assist anyone who wants to tackle this, but I don't think it yields many benefits for the work that is involved, which is probably a good month or two minimum. I simply cannot dedicate that much time on top.
* Anything left over in #7 is now just performance and merging declarations. Performance is our priority for v4, and then we can look at declaration merging.
