### ISSUE TITLE
mergeLonghand is NOT SAFE! here is a case

### ISSUE THREAD

**Issue by fjc0k** [ben-eb/cssnano#461]
raw css (generated by stylus mixin):

```css
border: 0 solid rgba(0, 0, 0, 0.2);
border-top-width: 1px;
border-right-width: 1px;
border-bottom-width: 1px;
border-left-width: 1px;
```

minified css with `mergeLonghand = true`:

```css
border: 0 solid rgba(0, 0, 0, 0.2);
border: 1px;
```

**Comment by evilebottnawi** [comment]
@fjc0k what version `cssnano` you use?

**Comment by fjc0k** [comment]
@evilebottnawi 3.10.0

**Comment by evilebottnawi** [comment]
@fjc0k can you try latest version `rc`?

**Comment by andyjansson** [comment]
``` 
npm i cssnano@next
```

**Comment by prettyv** [comment]
I think what @fjc0k means is that the merge result should be

**Comment by fjc0k** [comment]
@evilebottnawi sorry, now i can’t test it. The worng is as @prettyv said.

**Comment by evilebottnawi** [comment]
@fjc0k what result expected?

**Comment by fjc0k** [comment]
@evilebottnawi border: 0 solid rgba(0, 0, 0, 0.2); border-width: 1px;

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by An-Tu** [comment]
@fjc0k Are you sure that
`border: 0 solid rgba(0, 0, 0, 0.2);
border-top-width: 1px;
border-right-width: 1px;
border-bottom-width: 1px;
border-left-width: 1px;`
must be 
`border: 0 solid rgba(0, 0, 0, 0.2); border-width: 1px;`
?

Because I tested it locally, and i got this
`border: 1px solid rgba(0, 0, 0, 0.2);`

**Comment by fjc0k** [comment]
@An-Tu Oh, I think 
```css
border: 0 solid rgba(0, 0, 0, 0.2);
border-width: 1px;
```
is equal to
```css
border: 1px solid rgba(0, 0, 0, 0.2);
```
What I want to say is that the result is wrong, not the form.
