### ISSUE TITLE
Error: Cannot find module 'cssnano'

### ISSUE THREAD

**Issue by vitaly-zdanevich** [ben-eb/cssnano#477]
This is my first experience with cssnano, I did the steps from http://cssnano.co/guides/getting-started.

**Comment by vitaly-zdanevich** [comment]
Aha I found that I need to run `postcss --use cssnano --output.css input.css` and  `postcss.config.js` is not needed - maybe updating of Getting Started guide will simplify life for future fellows.

**Comment by andyjansson** [comment]
Yeah, sorry, the documentation on the website is for v4.x, not for v3.x. It's an unfortunate reality which should be rectified sometime in the future.
