### ISSUE TITLE
cssnano compress the invalid border property value

### ISSUE THREAD

**Issue by Guobacai** [ben-eb/cssnano#484]
Issue Description:

I have an invalid border property value:

`border: 0 0 7px 7px solid transparent;`

cssnano compress it into:

`border: 7px solid transparent;`

which makes this "border" property valid.

How can it be disabled?

**Comment by evilebottnawi** [comment]
@Guobacai can you test with using `cssnano@next`?

**Comment by Guobacai** [comment]
Hi @evilebottnawi 

Thanks for your quick response. 
I tried cssnano@next

Here is the result:

`border: 0 0 7x 7x solid transparent` 

is turned into:

`border-color: transparent;
  border-style: solid;
  border-width: 7px;
`

I would expect the border-width should be "0 0 7px 7px".

**Comment by evilebottnawi** [comment]
@Guobacai PR welcome

**Comment by An-Tu** [comment]
@evilebottnawi Hi! I will try to solve this problem. But I'm not sure how right.
Invalid border property should remain invalid?
```css
border: 0 0 7px 7px solid transparent
```
Or should we do something like that?
```css
border: solid transparent;
border-width: 0 0 7px 7px;
```

**Comment by evilebottnawi** [comment]
@An-Tu `border: 0 0 7px 7px solid transparent;` should be output as is, maybe it is already fixed, need add test and check
