### ISSUE TITLE
Cannot use cssnano with postcss-cli

### ISSUE THREAD

**Issue by dfcreative** [ben-eb/cssnano#5]
Faced the same issue as https://github.com/cssnext/cssnext/issues/98

```
$ postcss -u cssnano index.css -o bundle.css
[TypeError: object is not a function]
```

Probably that's the case https://github.com/code42day/postcss-cli/issues/11

**Comment by ben-eb** [comment]
Yep. Both of our modules use a similar architecture; I couldn't figure out a good way to expose cssnano as a PostCSS processor via something like `postcss.plugin('cssnano', fn);`, so to consume it you will have to use the `postcss.use` API. Or, use stdio redirections from the CLI.

**Comment by dfcreative** [comment]
@ben-eb :smile: yep https://github.com/code42day/postcss-cli/issues/8

**Comment by tunnckoCore** [comment]
> I couldn't figure out a good way to expose cssnano as a PostCSS processor via something like

when I refactoring the index I almost found the way, :smile: soo okey, will try.

**Comment by ben-eb** [comment]
I will tackle this in 2.0 as it means breaking the current API. For more details see https://github.com/ben-eb/cssnano/issues/15

**Comment by ben-eb** [comment]
Seems like this was fixed in https://github.com/code42day/postcss-cli/issues/11.
