### ISSUE TITLE
After PostCSS update to 5.0.x cssnano does not delete comments

### ISSUE THREAD

**Issue by azat-io** [ben-eb/cssnano#51]
![screenshot 2015-08-25 13 04 52](https://cloud.githubusercontent.com/assets/5698350/9464160/4c8a478a-4b2a-11e5-8bbd-20e1fac17441.png)

**Comment by ben-eb** [comment]
To save repeating myself: https://github.com/ben-eb/postcss-merge-rules/issues/8#issuecomment-133677166

**Comment by azat-io** [comment]
@ben-eb Ok. Thanks for your answer.

**Comment by ben-eb** [comment]
Fixed since https://github.com/ben-eb/cssnano/commit/37a36c2c0db0deb082e7522fe90747fdbfc9545f.

**Comment by azat-io** [comment]
@ben-eb Thank you!
