### ISSUE TITLE
Screenshot testing

### ISSUE THREAD

**Issue by ai** [ben-eb/cssnano#55]
We with @TrySound invented good way to test cssnano.

Right now we have many tools to test CSS based on screenshots. In real project they work badly, but for CSS minifiers this screenshot based tests are awesome:
1. We get some CSS from Twitter, Bootstrap and other popular project. And store it in ome special repo. There is not need to update and change this CSS.
2. We run some webkit engine from npm and save ideal screenshots in repo.
3. We process these CSS through cssnano.
4. We make screenshots for these processed CSS and compare them pixel-to-pixel with ideal screenshots.

There is two way to make css minifier popular: size and trust. I think there is no css minifier with testing, so if will have really good test cases, we can promote cssnano as trusted minifiers.

**Comment by ben-eb** [comment]
Pull requests for this would be very welcome. :+1:

**Comment by evilebottnawi** [comment]
@ai @ben-eb maybe add also testing together with other minification utilities (example clean-css). And refresh page with test every time new version cssnano and other minification utilities. This would help to assess the quality and speed of other utilities.

**Comment by ben-eb** [comment]
I mentioned this in https://github.com/ben-eb/cssnano/issues/46 but I will repost:

Screenshot testing is a *really big project* which I will not get time to do. I am happy to assist anyone who wants to tackle this, but I don't think it yields many benefits for the work that is involved, which is probably a good month or two minimum. I simply cannot dedicate that much time on top.

**Comment by ben-eb** [comment]
I'm quite happy with the work done in https://github.com/Deeech/css-minificator-tests so I'm going to use this for screenshot testing moving forward. 😄

**Comment by evilebottnawi** [comment]
@ben-eb some errors :smile:

**Comment by ben-eb** [comment]
@evilebottnawi Yeah, we're too aggressive by default. I already sent a patch to include the safe version too (which passes all tests). https://github.com/Deeech/css-minificator-tests/pull/5
