### ISSUE TITLE
Why convert pixels to pica?

### ISSUE THREAD

**Issue by oliverfarrell** [ben-eb/cssnano#6]
Hopefully just a quick question. I'm intrigued as to why you convert pixel values to pica? I'm just having a play with cssnano and spotted that it does this, but only for values that are equal to 16px (in my case anyway).

**Comment by ben-eb** [comment]
It's a micro-optimisation. :smile:

https://github.com/ben-eb/postcss-convert-values/issues/1

**Comment by oliverfarrell** [comment]
Ah! Neat! :+1:
