### ISSUE TITLE
Option to keep whitespace?

### ISSUE THREAD

**Issue by vitorgalvao** [ben-eb/cssnano#65]
This may be a weird request, but is there an option to *not* remove whitespace? Not finding it in the documentation, if there is one.

My use case is simple: I was reading everything `cssnano` does and though “most of these I’d like to have applied to my development CSS” (like removing empty rules and deduplicating, for example), but for that CSS to still make sense, I’d need the whitespace there, naturally.

**Comment by ben-eb** [comment]
Sort of. You can disable the `core` module (`--no-core` on the CLI, or `{core: false}` in JS) which will keep most of the line breaks. Note that whitespace is transformed by a few different modules as well, so you might have to play with the other options a bit to get what you want. :smile:

The other route would be to beautify your CSS afterwards, using something like https://github.com/ben-eb/perfectionist.
