### ISSUE TITLE
Replaces «px» with «pc»

### ISSUE THREAD

**Issue by Kiryous** [ben-eb/cssnano#67]
After several runs cssnano replaces «px» with «pc» in some classes

**Comment by TrySound** [comment]
@Kiryous Yes, couse value becomes smaller. Check [postcss-convert-values](https://github.com/ben-eb/postcss-convert-values)

**Comment by tunnckoCore** [comment]
@TrySound from `px` to `pc` smaller, again 2 symbols? absolutely interesting, lol.

**Comment by TrySound** [comment]
@tunnckoCore @Kiryous  `16px`->`1pc`

**Comment by tunnckoCore** [comment]
oh, yes, really - i've just forgot it. thanks.

**Comment by ben-eb** [comment]
It's disabled by default since 3.2.0. Use `{convertValues: {length: false}}` to re-enable.
