### ISSUE TITLE
Improvements - what will help make this more production ready?

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/cssnano#7]
I am going to pause development of this project for a few weeks until all of my deadlines are met, and hope to resume around the 16th of May. I just wanted to get some thoughts down on what I mean by the first line of the README:

> Note that this project is still a work in progress, and needs more testing before it can be recommended to use in production. There are some optimisations that need to be further expanded upon, and others yet to be written.

In my mind, the other stand-out project for minifying CSS is clean-css, which offers really good advanced compression. So, people using cssnano should be aware that clean-css may offer better compression, while fine tuning is still being done on each PostCSS processor. For example, there is a critical bug in postcss-minify-selectors, and an optimisation that should be made for postcss-convert-values:

* ~~https://github.com/ben-eb/postcss-minify-selectors/issues/2~~ (done)
* ~~https://github.com/ben-eb/postcss-convert-values/issues/2~~ (done)

Also note that cssnano has no built in logic for removing browser specific hacks, which csswring and clean-css provide. I think such a module needs fine control over browser support, like Autoprefixer, so I didn't just want to remove those styles, as yes there are still people using things like IE6 (that's why cssgrace exists), even though it is a dead browser. I have had some more ideas for optimisations that I would love to consume in cssnano, and if anyone would like to turn these into PostCSS processors, please do so and post here that you're working on them!

* ~~A processor for removing vendor specific hacks.~~ (done, will be default in v3)
* ~~A processor for running inline svg through SVGO.~~ (done, will be default in v3)
* ~~postcss-discard-font-face should be deprecated, and the logic should be expanded to form a new postcss-discard-unused module - that is responsible for discarding font faces, keyframes, and counter styles.~~ (done)
* A processor that can properly handle overridden properties, whilst taking into account fallbacks, such as a transparent color falling back to a solid color.
* ~~A processor that knows browser defaults and can remove unnecessary values.~~ (not safe)
* ~~A processor that is aware of `currentColor` and can compress this example:~~ (not *categorically* safe, see http://jsfiddle.net/a1gc58on/)

```css
h1 {
  color: orange;
  border: 1px solid orange;
}
```

To:

```css
h1 {
  color: orange;
  border: 1px solid;
}
```

Of course, you can also help by testing cssnano on your CSS files and observing the output. The main issue is this minify-selectors bug, so that will be my main priority once I resume work on the module.

**Comment by ScottSmith95** [comment]
I think the speed of cssnano is the main aspect that is holding me back from replacing csswring or clean-css in my projects. Both of those processors are usually [at least twice as fast](http://goalsmashers.github.io/css-minification-benchmark/). 

CSS minification is a very competitive space, with plenty of projects vying for the top spot, the other projects all fare just the same in compression for my projects so the speed with which changes are output is the biggest deciding factor for me.

**Comment by ben-eb** [comment]
@ScottSmith95 Yes, that is an important point. cssnano's goal is to be more modular, and in so doing there is repetitive work that each module in the chain is performing. This is something that we want to address with PostCSS itself - an API that handles repetitive value transformations, so that plugins do not have to split string, map over values, and stringify again. Thanks for your feedback. :smile:

**Comment by ScottSmith95** [comment]
@ben-eb I assumed that this was the reason, and that is perfectly reasonable.

**Comment by TrySound** [comment]
@ScottSmith95 Stay tuned and don't forget to follow! :)

**Comment by tavriaforever** [comment]
If something will happening with speed, we will try use it :metal:

**Comment by benfrain** [comment]
Just to chime in on the speed issue. I'm using it via gulp at present and without cssnano the compile time is 2.71s. With cssnano it is 10s. On any significant codebase having cssnano running on anything other than a production build starts to become painful. Any speed improvements would be great.

**Comment by ben-eb** [comment]
@benfrain One thing that you might want to try is using a full PostCSS build step, to cut down on parse/stringify/parse times, since https://github.com/ben-eb/cssnano/issues/26 was fixed. But yes, speed is an important area which was sacrificed somewhat for modularity.

**Comment by ben-eb** [comment]
Update on speed; we've been working on cutting AST iterations dramatically this week, so this should go some way into speeding up the performance. Lots of module test suite running times have been cut in half with these changes; but of course there is still more to do. :smile:

**Comment by ben-eb** [comment]
For anyone tracking the speed issue, new versions perform much better since we refactored postcss-discard-duplicates; I see improvements of 50% or more.

https://github.com/ben-eb/cssnano/issues/47#issuecomment-136654859

**Comment by jedmao** [comment]
@ben-eb how would you describe cssnano's production-ready state at this point? Are there any major items left that need to be addressed?

**Comment by ben-eb** [comment]
@jedmao I think we can make it faster, that seems to be our pain point right now. However since the discard-duplicates refactor speed improved dramatically, it is more comparable with similar tools such as clean-css.

What I would say is cssnano is production ready, but your mileage may vary with regard to how much compression you get. All minifiers have different levels of support for different compression techniques; I introduced a few different 'new' optimisations such as 3d transforms (https://github.com/ben-eb/postcss-reduce-transforms) but haven't completed others (the main one being declaration merging https://github.com/ben-eb/cssnano/issues/86, but I want to get this right). I also wrote a test suite (https://github.com/ben-eb/css-minifier-tests) with a lot of edge cases that we pass.

I think it would be best to try it out and see if you have any problems.

**Comment by ben-eb** [comment]
I'm going to go ahead and close this issue as it has outlived its usefulness right now, with issues in here being discussed in separate threads;

* The remaining optimisation of declaration merging is being tracked in https://github.com/ben-eb/cssnano/issues/86.
* Performance is still a key issue but we need time for this to be addressed properly. We are trying to make this module more performant, see both https://github.com/ben-eb/cssnano/issues/47 & https://github.com/ben-eb/cssnano/issues/88.
