### ISSUE TITLE
Problem with list-style: none

### ISSUE THREAD

**Issue by stenmuchow** [ben-eb/cssnano#75]
After running cssnano i noticed that all my list items now had bullets next to them. This is strange because i have a reset style sheet that removes the list style. After looking at my nanoed code I notice that my list-style: none now consists of:
```
ul{list-style:function (a) { return condition.apply(this,arguments) ? extendedFn.apply(this,arguments):nativeFn.apply(this,arguments); }}
```

Seems like something is going wrong...

**Comment by ben-eb** [comment]
How do I reproduce this? Latest CLI:

```css
ul { list-style: none }
```

Output:

```css
ul{list-style:none}
```

**Comment by stenmuchow** [comment]
@ben-eb - Indeed I get the same results with the CLI. 

My build process is thru gulp, I have a yeoman scaffold using [gulp-angular-generator](https://github.com/Swiip/generator-gulp-angular) and where in the past the generator was using csso for minification, I dropped in cssnano. There is a problem with stripping of 's' from '0s' but this has nothing to do with cssnano.

Here is my [build.js](https://gist.github.com/stenmuchow/4426d7f223c7da348a3e)

**Comment by TrySound** [comment]
@stenmuchow Problem with 0s is stripping or you want 's' will be stripped?

**Comment by stenmuchow** [comment]
@TrySound - No i dont want them stripped and neither does chrome or else the rule:
```
transition-duration: 0s;
```

won't work. 

CSSO - strips zeros, but seems there is a commit in place to fix, but needs to be merged.
UGLIFY-CSS - strips zeros, not fix in place.
CSSNANO - no stripping, but i have other weird behavior.

**Comment by TrySound** [comment]
@stenmuchow Why `transition-duration: 0s;` won't work? It works fine. `transition-duration: 0;` won't work in firefox as I know.

**Comment by TrySound** [comment]
@stenmuchow Try to reproduce your problem with smallest case. Remove all non-css packages to locate the problem.

**Comment by ben-eb** [comment]
Does your `list-style` problem still occur without using cssnano?

**Comment by stenmuchow** [comment]
@ben-eb  - no that's why i know it was something to do with cssnano...

**Comment by stenmuchow** [comment]
@TrySound - I think u misunderstood me... 

Works in Chrome, Firefox, etc...
```
transition-duration: 0s;
```

Doesnt work in forementioned browsers
```
transition-duration: 0;
```

**Comment by ben-eb** [comment]
@stenmuchow Could you attach some sample CSS and a package.json to your gist so that I could reproduce this error?

**Comment by stenmuchow** [comment]
[index.css](https://gist.github.com/stenmuchow/f8dd4a0f4900421d78fe)
[package.json](https://gist.github.com/stenmuchow/d7c022a9a98c6ecbbc21)

**Comment by ben-eb** [comment]
Thanks. How do I run this, and do I need any other supporting files? Not a typical gulpfile setup, & the `inject` task is not defined. :smile:

**Comment by stenmuchow** [comment]
Its a yeoman generated gulp build. The generator link is above. I will try and make a simplified version of it...

**Comment by stenmuchow** [comment]
OK I have figure out how to reproduce this...

1. install the angular scaffold application using [gulp-angular-generator](https://github.com/Swiip/generator-gulp-angular) - all default values, just hit enter all the way through.

2. install gulp-cssnano

3. open gulp/build.js and replace line #50
```
      .pipe($.cssnano())
```

4. open src/app/index.scss and add a line for list-style: none
```
ul {
  list-style: none;
}
```

5. gulp build

6. check the output in dist/styles/app-*.css

**Comment by ben-eb** [comment]
Thanks, have done so. I can't reproduce this! I've tried both just adding the `ul { list-style: none }` to the existing Sass boilerplate, which worked as expected, then tried replacing all of that boilerplate with that one line, and it again worked as expected.

Is there anything I'm missing here?

**Comment by stenmuchow** [comment]
wow... then i am completely confused... Sandboxing it into this new environment with a new gulp build gave me this error as well, but if you still cant reproduce I am at a loss where to go. thanks anyways...

**Comment by ben-eb** [comment]
Which version of Node are you running?

**Comment by stenmuchow** [comment]
v0.12.2

**Comment by ben-eb** [comment]
@stenmuchow Can you try a reinstall of cssnano please? I think this was a fault with postcss-merge-idents not checking own properties, a fix was released for it in the latest version (2.1.3).

**Comment by stenmuchow** [comment]
@ben-eb - Awesome! Looks like its fixed! Thanks. You can close...

**Comment by ben-eb** [comment]
:+1:
