### ISSUE TITLE
Invalid minification of translate

### ISSUE THREAD

**Issue by lo1tuma** [ben-eb/cssnano#76]
With cssnano version `3.3.0` the following code

```css
transform: translate(-50%, -50%);
```

will be minified to

```css
transform:translate(-50%);
```

which is not equivalent and breaks our layout.

**Comment by ben-eb** [comment]
`translate(-50%)` is shorthand for `translate(-50%, -50%)`.

https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#translate()

**Comment by ben-eb** [comment]
OK, turns out that the spec says differently. Will revert.

http://www.w3.org/TR/css3-transforms/#funcdef-translate

**Comment by ben-eb** [comment]
Fixed by https://github.com/ben-eb/postcss-reduce-transforms/commit/c378f90168786cfeffab5be6daf660375e2300ce. Thanks for reporting. :+1:

**Comment by lo1tuma** [comment]
Thank you. Awesome response time.
