### ISSUE TITLE
css-minification-benchmark results

### ISSUE THREAD

**Issue by neonick** [ben-eb/cssnano#78]
Hi, Ben! 
I found a link to [css-minification-benchmark](https://github.com/GoalSmashers/css-minification-benchmark). Based on the [information](http://goalsmashers.github.io/css-minification-benchmark/) in it now cssnano slowest, in comparison with the others. Perhaps this information will be of interest to you.

**Comment by neonick** [comment]
Sorry, I looked at the closed issues and understand that you are informed a long time.

**Comment by ben-eb** [comment]
Yep, actually I sent in a couple of patches for that. But it's using the old 2.x releases, we are async since 3.x. :smile:
