### ISSUE TITLE
merge option 

### ISSUE THREAD

**Issue by magsout** [ben-eb/cssnano#8]
```
var fs = require("fs")
var nano = require("..")
var postcss   = require('postcss');

var input = fs.readFileSync("input.css", "utf8")

var output =
     postcss()
     .use(nano( {
       calc: false,
       merge : false,
       comments : {
         removeAll : true
       }
    }
   ))
   .process(input).css

fs.writeFileSync("index.output.css", output)
console.log(output)

```

input.css : 

```


/*! heading */
h1 {
	margin:0 auto;
	z-index:2;
	font-size: calc((3px * 2 - 1px));
}
/*! heading 2 */
h2 {
	color:red;
	z-index:3;
	margin-top:2px;
	margin-right:1px;
	margin-bottom:2px;
	margin-left:1px;
}
```

output.css

```
h1{margin:0 auto;z-index:1;font-size:calc((3px * 2 - 1px))}h2{color:red;z-index:2;margin:2px 1px}
```

**Comment by ben-eb** [comment]
This is handled internally and not part of postcss-merge-rules. But you are correct, it should be optional.

**Comment by magsout** [comment]
Why when I put merge to false, the merging is done anyway?

**Comment by ben-eb** [comment]
The logic for this is an internal part of cssnano. https://github.com/ben-eb/cssnano/tree/master/lib - support for merging values is only partially done. postcss-merge-rules will only merge whole rulesets, something like postcss-merge-declarations should be done as a separate module. But, I haven't had the time for this just yet.

**Comment by magsout** [comment]
Ok thanks ;)

**Comment by ben-eb** [comment]
@magsout By the way, this was extracted out yesterday. :smile:

https://github.com/ben-eb/postcss-merge-longhand

**Comment by magsout** [comment]
👍
