### ISSUE TITLE
Implement a global browsers option

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/cssnano#80]
I'd like to expand the `browsers` option in the bundled autoprefixer package to be a global setting, so that other optimisations that may provide legacy support can all use the same settings. For example, https://github.com/ben-eb/postcss-merge-rules/pull/9.

The patch should load browserslist in its default settings, and some detection should be used to ensure that people use `{browsers: 'last 3 versions'}` rather than `{autoprefixer: {browsers: 'last 3 versions'}}`. cssnano could console log a message to say use the top level option instead.

**Comment by yisibl** [comment]
Nice!
