### ISSUE TITLE
Pass `sourcemap` option from inside PostCSS config file

### ISSUE THREAD

**Issue by Francisc** [ben-eb/cssnano#82]
Hello,

Is it possible to pass the `--sourcemap` option from inside the PostCSS config file?
This is what I currently have and it fails:

```
{
	"use": ["autoprefixer", "cssnano"],
	"autoprefixer": {
		"browsers": ["last 2 versions", "> 5%"]
	},
	"cssnano": {
		"sourcemap": true
	}
}
```

**Comment by TrySound** [comment]
@Francisc sourcemaps can't work only on some plugins. It's global config thing. So move this issue to postcss-cli.

**Comment by Francisc** [comment]
Thank you for the very quick response.
The `postcss-cli` project is currently working on this so it's not supported yet.
I understand sourcemaps don't work this way, but the advantage (read as *temporary solution*) of being able to ask cssnano was I could see output after autoprefixer, so before the optimization performed by cssnano.

**Comment by TrySound** [comment]
@Francisc cssnano do not generate sourcemaps. It's just a plugin for postcss which builds ast in string and sourcemaps. Better use script with postcss call or gulp-postcss

**Comment by Francisc** [comment]
Right, makes sense.
Doing `postcss --options-here | cssnano > style.css --sourcemap` was giving me that quick fix I mentioned. But I understand what you're saying, it was PostCSS doing the sourcemap generation, cssnano was just passing the config to it.

**Comment by TrySound** [comment]
@Francisc Yeah, you just use here two separate cli with two postcss instances.

**Comment by Francisc** [comment]
Got it. Thanks a bunch for helping me understand.
