### ISSUE TITLE
Consolidate dependencies/utilities

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/cssnano#95]
For v4 we will need to normalise dependencies across all sub-modules. I don't mind switching to utilities like lo-dash but our test suite and benchmarks need to be more thorough than they are right now.

https://github.com/ben-eb/postcss-zindex/pull/4

**Comment by TrySound** [comment]
@ben-eb Need to test all external utilites and pr them if something not good :)

**Comment by ben-eb** [comment]
Resolved in https://github.com/ben-eb/cssnano/releases/tag/v4.0.0-rc.0.
